export default {
  aritmetica: {
    facil: {
      titulo: "Operaciones Básicas",
      contenido: [
        { tipo: "intro", texto: "La aritmética es la base de todas las matemáticas. En esta lección aprenderás las cuatro operaciones fundamentales que usarás en tu vida diaria." },
        { tipo: "concepto", titulo: "Suma (+)", texto: "La suma une dos o más cantidades en una sola. Es la operación más básica y el punto de partida de toda la aritmética.", subItems: ["15 + 8 = 23", "100 + 250 = 350", "0.5 + 0.3 = 0.8"] },
        { tipo: "concepto", titulo: "Resta (−)", texto: "La resta indica la diferencia entre dos cantidades. Es la operación inversa de la suma.", subItems: ["23 - 8 = 15", "50 - 18 = 32", "100 - 75 = 25"] },
        { tipo: "ejemplo", titulo: "Ejercicio práctico", texto: "Si tienes S/. 50 y compras algo por S/. 18, ¿cuánto cambio recibes?", pasos: ["Partimos de S/. 50", "Restamos el precio: 50 - 18", "Resultado: S/. 32 de cambio"] },
        { tipo: "formula", formula: "a − b = c", descripcion: "Donde 'a' es el minuendo, 'b' el sustraendo y 'c' la diferencia." },
        { tipo: "concepto", titulo: "Multiplicación (×)", texto: "La multiplicación es suma repetida de forma abreviada. 6 × 4 significa sumar 6 cuatro veces: 6+6+6+6 = 24.", subItems: ["7 × 3 = 21", "12 × 5 = 60", "9 × 9 = 81"] },
        { tipo: "concepto", titulo: "División (÷)", texto: "La división reparte una cantidad en partes iguales. Es la operación inversa de la multiplicación.", subItems: ["36 ÷ 6 = 6 (porque 6×6=36)", "100 ÷ 4 = 25", "20 ÷ 5 = 4"] },
        { tipo: "ejemplo", titulo: "Combinando operaciones", texto: "Si compras 3 cuadernos a S/. 12 c/u y pagas con S/. 50:", pasos: ["Primero multiplicamos: 3 × 12 = S/. 36", "Luego restamos: 50 - 36 = S/. 14", "Tu cambio es S/. 14"] },
        { tipo: "tabla", titulo: "Tabla de valores comunes", fila: [["2 × 1", "2"], ["2 × 2", "4"], ["2 × 3", "6"], ["2 × 4", "8"], ["2 × 5", "10"], ["2 × 6", "12"], ["2 × 7", "14"], ["2 × 8", "16"], ["2 × 9", "18"], ["2 × 10", "20"]] },
        { tipo: "resumen", items: ["La suma (+) une cantidades", "La resta (−) indica diferencia", "La multiplicación (×) es suma repetida", "La división (÷) reparte en partes iguales", "Las operaciones se pueden combinar en un solo problema"] },
        { tipo: "tip", texto: "Consejo: Practica las tablas de multiplicar todos los días. En 10 minutos al día las dominarás en pocas semanas." },
      ],
    },
    medio: {
      titulo: "Fracciones y Porcentajes",
      contenido: [
        { tipo: "intro", texto: "Las fracciones y porcentajes nos permiten trabajar con partes de un todo. Son herramientas esenciales para comprender descuentos, impuestos y proporciones." },
        { tipo: "concepto", titulo: "¿Qué es una fracción?", texto: "Una fracción representa una parte de un todo. Tiene dos partes: numerador (arriba) y denominador (abajo).", subItems: ["3/4 significa 3 partes de 4 iguales", "1/2 es la mitad de algo", "5/8 son 5 partes de un todo dividido en 8"] },
        { tipo: "formula", formula: "a/b + c/b = (a+c)/b", descripcion: "Para sumar fracciones con el mismo denominador, solo suma los numeradores." },
        { tipo: "ejemplo", titulo: "Suma de fracciones", texto: "Sumar 2/5 + 1/5:", pasos: ["Mismo denominador (5)", "Sumamos numeradores: 2 + 1 = 3", "Resultado: 3/5"] },
        { tipo: "ejemplo", titulo: "Fracciones con distinto denominador", texto: "Sumar 1/3 + 1/4:", pasos: ["Buscamos el MCM de 3 y 4 → 12", "Convertimos: 4/12 + 3/12", "Resultado: 7/12"] },
        { tipo: "concepto", titulo: "Porcentajes", texto: "Un porcentaje es una fracción cuyo denominador es 100. El símbolo % significa 'por ciento'.", subItems: ["25% = 25/100 = 1/4 = 0.25", "50% = 50/100 = 1/2 = 0.5", "100% = 100/100 = 1 entero"] },
        { tipo: "ejemplo", titulo: "Calcular porcentajes", texto: "¿Cuánto es el 30% de S/. 200?", pasos: ["Convertimos: 30% = 0.30", "Multiplicamos: 200 × 0.30", "Resultado: S/. 60"] },
        { tipo: "tabla", titulo: "Conversiones rápidas", fila: [["1/2", "50%"], ["1/4", "25%"], ["3/4", "75%"], ["1/3", "33.3%"], ["1/5", "20%"], ["1/10", "10%"]] },
        { tipo: "resumen", items: ["Fracción = numerador / denominador", "Mismo denominador → suma directa", "Distinto denominador → busca el MCM", "% = fracción sobre 100", "Para hallar X% de un número: multiplica por X/100"] },
        { tipo: "tip", texto: "Consejo: Para convertir fracción a porcentaje, multiplica por 100. Ej: 3/4 = 0.75 = 75%." },
      ],
    },
    dificil: {
      titulo: "Potencias, Raíces y Números Primos",
      contenido: [
        { tipo: "intro", texto: "Las potencias y raíces son operaciones que van más allá de la suma y multiplicación básica. Los números primos son los bloques fundamentales de los números enteros." },
        { tipo: "concepto", titulo: "Potencias", texto: "Una potencia es multiplicación repetida de un número por sí mismo. Se escribe como base elevada a un exponente.", subItems: ["2³ = 2×2×2 = 8", "5² = 5×5 = 25", "3⁴ = 3×3×3×3 = 81", "10ⁿ agrega n ceros: 10³ = 1000"] },
        { tipo: "formula", formula: "aⁿ = a × a × ... × a (n veces)", descripcion: "La base 'a' se multiplica por sí misma 'n' veces." },
        { tipo: "ejemplo", titulo: "Potencias paso a paso", texto: "Calcular 2⁴ + 3²:", pasos: ["2⁴ = 2×2×2×2 = 16", "3² = 3×3 = 9", "Sumamos: 16 + 9 = 25"] },
        { tipo: "concepto", titulo: "Raíces cuadradas", texto: "La raíz cuadrada es la operación inversa de elevar al cuadrado. √x = número que multiplicado por sí mismo da x.", subItems: ["√144 = 12 (porque 12² = 144)", "√25 = 5 (porque 5² = 25)", "√81 = 9 (porque 9² = 81)"] },
        { tipo: "ejemplo", titulo: "Combinando raíces y potencias", texto: "Resuelve: √(196) + 3²", pasos: ["√196 = 14 (porque 14×14 = 196)", "3² = 9", "Sumamos: 14 + 9 = 23"] },
        { tipo: "concepto", titulo: "Números primos", texto: "Un número primo solo es divisible entre 1 y sí mismo. Son los 'ladrillos' con los que se construyen todos los demás números.", subItems: ["Primos menores a 30: 2, 3, 5, 7, 11, 13, 17, 19, 23, 29", "El 2 es el único primo par", "El 1 NO es primo"] },
        { tipo: "tabla", titulo: "Primeros 10 números primos", fila: [["2", "Primo (único par)"], ["3", "Primo"], ["5", "Primo"], ["7", "Primo"], ["11", "Primo"], ["13", "Primo"], ["17", "Primo"], ["19", "Primo"], ["23", "Primo"], ["29", "Primo"]] },
        { tipo: "resumen", items: ["aⁿ = base elevada a exponente", "√a = raíz cuadrada de a", "a⁰ = 1 (cualquier número elevado a 0)", "Los primos son divisibles solo por 1 y ellos mismos", "Usa la criba de Eratóstenes para encontrar primos"] },
        { tipo: "tip", texto: "Consejo: Para saber si un número es primo, intenta dividirlo entre todos los primos menores que su raíz cuadrada." },
      ],
    },
  },
  algebra: {
    facil: {
      titulo: "Introducción al Álgebra",
      contenido: [
        { tipo: "intro", texto: "El álgebra usa letras (variables) para representar números desconocidos. Es como resolver un rompecabezas donde faltan piezas." },
        { tipo: "concepto", titulo: "Variables y constantes", texto: "Una variable es una letra que representa un número desconocido. Una constante es un valor fijo que no cambia.", subItems: ["Variables: x, y, z, a, b", "Constantes: 5, -3, 100, 0.5", "Cuando decimos 'x = 7', encontramos el valor de la variable"] },
        { tipo: "ejemplo", titulo: "Encontrar x", texto: "Si x + 5 = 12, ¿cuánto vale x?", pasos: ["Ecuación: x + 5 = 12", "Restamos 5 de ambos lados", "x = 12 - 5 = 7", "Verificación: 7 + 5 = 12 ✓"] },
        { tipo: "concepto", titulo: "Propiedad de la igualdad", texto: "Lo que haces de un lado de la ecuación, debes hacer del otro. Si sumas 5 a un lado, suma 5 al otro también.", subItems: ["Si a = b, entonces a + c = b + c", "Si a = b, entonces a - c = b - c", "Si a = b, entonces a × c = b × c"] },
        { tipo: "formula", formula: "Si ax + b = c, entonces x = (c − b) / a", descripcion: "Fórmula general para ecuaciones de primer grado con una incógnita." },
        { tipo: "ejemplo", titulo: "Simplificar expresiones", texto: "Simplifica: 3a + 2a + 5", pasos: ["Agrupamos términos semejantes: 3a + 2a = 5a", "Resultado: 5a + 5", "Podemos factorizar: 5(a + 1)"] },
        { tipo: "resumen", items: ["Las variables representan números desconocidos", "Despejar = dejar la variable sola", "Operación igual en ambos lados mantiene el equilibrio", "Verifica siempre sustituyendo el resultado"] },
        { tipo: "tip", texto: "Consejo: Siempre verifica tu respuesta sustituyendo el valor de la variable en la ecuación original." },
      ],
    },
    medio: {
      titulo: "Factorización y Ecuaciones",
      contenido: [
        { tipo: "intro", texto: "La factorización es descomponer expresiones en productos de factores más simples. Es clave para resolver ecuaciones cuadráticas." },
        { tipo: "concepto", titulo: "Diferencia de cuadrados", texto: "a² - b² = (a+b)(a-b). Esta identidad se usa constantemente para factorizar y simplificar.", subItems: ["x² - 9 = (x+3)(x-3)", "4x² - 25 = (2x+5)(2x-5)", "16 - y² = (4+y)(4-y)"] },
        { tipo: "formula", formula: "a² − b² = (a+b)(a−b)", descripcion: "Diferencia de cuadrados: un patrón que aparece frecuentemente." },
        { tipo: "concepto", titulo: "Trinomio cuadrado perfecto", texto: "x² + 2bx + b² = (x+b)². Es un patrón que se reconoce por tener el término lineal exactamente doble de la raíz del término constante.", subItems: ["x² + 6x + 9 = (x+3)² (porque 6 = 2×3)", "x² - 10x + 25 = (x-5)²", "4x² + 12x + 9 = (2x+3)²"] },
        { tipo: "ejemplo", titulo: "Factorizar trinomio", texto: "Factoriza x² - 5x + 6:", pasos: ["Buscamos dos números que multiplicados den 6 y sumados den -5", "Los números son -2 y -3: (-2)×(-3)=6 y (-2)+(-3)=-5", "Resultado: (x-2)(x-3)", "Verificación: x²-3x-2x+6 = x²-5x+6 ✓"] },
        { tipo: "formula", formula: "x² + (a+b)x + ab = (x+a)(x+b)", descripcion: "Factorización de trinomios: busca dos números cuya suma sea el coeficiente lineal y cuyo producto sea el término independiente." },
        { tipo: "ejemplo", titulo: "Resolviendo ecuación cuadrática", texto: "Resuelve x² - 5x + 6 = 0:", pasos: ["Factorizamos: (x-2)(x-3) = 0", "Si un producto es 0, uno de los factores es 0", "x-2 = 0 → x = 2, o x-3 = 0 → x = 3", "Soluciones: x = 2 y x = 3"] },
        { tipo: "tabla", titulo: "Patrones de factorización", fila: [["a² − b²", "(a+b)(a−b)"], ["a² + 2ab + b²", "(a+b)²"], ["a² − 2ab + b²", "(a−b)²"], ["x² + (a+b)x + ab", "(x+a)(x+b)"]] },
        { tipo: "resumen", items: ["Diferencia de cuadrados: a²-b² = (a+b)(a-b)", "Cuadrado perfecto: a²±2ab+b² = (a±b)²", "Para factorizar trinomios, busca dos números", "Verificar = expandir y comparar"] },
        { tipo: "tip", texto: "Consejo: Siempre verifica factorizando (expandiendo) tu resultado para comprobar que obtienes la expresión original." },
      ],
    },
    dificil: {
      titulo: "Sistemas de Ecuaciones",
      contenido: [
        { tipo: "intro", texto: "Un sistema de ecuaciones es un grupo de dos o más ecuaciones con las mismas variables. Resolver el sistema significa encontrar los valores que satisfacen todas las ecuaciones simultáneamente." },
        { tipo: "concepto", titulo: "Método de sustitución", texto: "Despeja una variable de una ecuación y sustitúyela en la otra. Es útil cuando una ecuación ya tiene una variable despejada.", subItems: ["Despeja y = ... de la primera ecuación", "Sustituye en la segunda ecuación", "Resuelve la ecuación resultante"] },
        { tipo: "ejemplo", titulo: "Sustitución paso a paso", texto: "Sistema: y = 10 - x y x + y = 10", pasos: ["Tenemos y = 10 - x", "Sustituimos en la segunda: x + (10-x) = 10", "Esto siempre da 10 = 10 → necesitamos otra información", "Revisamos: el sistema tiene infinitas soluciones"] },
        { tipo: "concepto", titulo: "Método de eliminación", texto: "Suma o resta ecuaciones para eliminar una variable. Es el método más rápido cuando los coeficientes son iguales o opuestos.", subItems: ["Igualar coeficientes de una variable", "Sumar o restar para eliminar", "Resolver la ecuación resultante"] },
        { tipo: "ejemplo", titulo: "Eliminación resuelta", texto: "Sistema: x + y = 10 y x - y = 4", pasos: ["Sumamos ambas ecuaciones: (x+y) + (x-y) = 10+4", "Resultado: 2x = 14, por lo tanto x = 7", "Sustituimos: 7 + y = 10, entonces y = 3", "Solución: (x, y) = (7, 3)"] },
        { tipo: "formula", formula: "Si ax + by = c y dx + ey = f", descripcion: "Sistema general de 2 ecuaciones con 2 incógnitas. Se puede resolver por sustitución o eliminación." },
        { tipo: "ejemplo", titulo: "Sistema con coeficientes", texto: "Resuelve: 2x + 3y = 12 y x - y = 1", pasos: ["De la segunda: x = y + 1", "Sustituimos: 2(y+1) + 3y = 12", "2y + 2 + 3y = 12 → 5y = 10 → y = 2", "x = 2 + 1 = 3. Solución: (3, 2)"] },
        { tipo: "tabla", titulo: "Cómo elegir el método", fila: [["Una variable despejada", "→ Sustitución"], ["Coeficientes iguales/opuestos", "→ Eliminación"], ["Coeficientes diferentes", "→ Multiplicar y luego eliminar"], ["Graficar soluciones", "→ Graficar ambas rectas"]] },
        { tipo: "resumen", items: ["Sustitución: despejar y reemplazar", "Eliminación: sumar/restar para eliminar variable", "Siempre verifica la solución en ambas ecuaciones", "Un sistema puede tener 1 solución, infinitas o ninguna"] },
        { tipo: "tip", texto: "Consejo: Verifica SIEMPRE sustituyendo ambos valores en ambas ecuaciones originales. Si ambas dan true, tu solución es correcta." },
      ],
    },
  },
  ecuaciones: {
    facil: {
      titulo: "Ecuaciones Simples",
      contenido: [
        { tipo: "intro", texto: "Una ecuación es una igualdad matemática con una incógnita. Resolverla significa encontrar el valor que hace que ambos lados sean iguales." },
        { tipo: "concepto", titulo: "Qué es una ecuación", texto: "Una ecuación tiene dos lados separados por el signo =. Tu trabajo es encontrar el valor de la variable que hace que ambos lados sean iguales.", subItems: ["x + 5 = 12 → ¿x = ?", "2x = 18 → ¿x = ?", "x/3 = 9 → ¿x = ?"] },
        { tipo: "ejemplo", titulo: "Resolución paso a paso", texto: "Resuelve: x + 8 = 15", pasos: ["Escribimos: x + 8 = 15", "Restamos 8 de ambos lados", "x = 15 - 8 = 7", "Verificamos: 7 + 8 = 15 ✓"] },
        { tipo: "concepto", titulo: "Propiedades de la igualdad", texto: "Puedes sumar, restar, multiplicar o dividir ambos lados por el mismo número sin cambiar la igualdad.", subItems: ["Sumar: a = b → a+c = b+c", "Restar: a = b → a-c = b-c", "Multiplicar: a = b → a×c = b×c", "Dividir: a = b → a÷c = b÷c"] },
        { tipo: "ejemplo", titulo: "Multiplicación y división", texto: "Resuelve: 2x = 18", pasos: ["Escribimos: 2x = 18", "Dividimos ambos lados entre 2", "x = 18 ÷ 2 = 9", "Verificamos: 2×9 = 18 ✓"] },
        { tipo: "formula", formula: "Si ax + b = c, entonces x = (c − b) / a", descripcion: "Fórmula general para despejar x en ecuaciones de primer grado." },
        { tipo: "ejemplo", titulo: "Ecuación con división", texto: "Resuelve: x/4 = 9", pasos: ["Escribimos: x/4 = 9", "Multiplicamos ambos lados por 4", "x = 9 × 4 = 36", "Verificamos: 36/4 = 9 ✓"] },
        { tipo: "resumen", items: ["Una ecuación tiene dos lados con un = entre ellos", "Despejar = dejar x solo en un lado", "Operaciones iguales en ambos lados", "Siempre verifica tu respuesta"] },
        { tipo: "tip", texto: "Consejo: El objetivo SIEMPRE es dejar la variable sola en un lado. Mueve los números al otro lado haciendo la operación inversa." },
      ],
    },
    medio: {
      titulo: "Ecuaciones con Paréntesis",
      contenido: [
        { tipo: "intro", texto: "Cuando una ecuación tiene paréntesis, primero debemos eliminarlos usando la propiedad distributiva antes de despejar la variable." },
        { tipo: "concepto", titulo: "Propiedad distributiva", texto: "a(b + c) = ab + ac. El número fuera del paréntesis se multiplica por cada término dentro del paréntesis.", subItems: ["3(x + 2) = 3x + 6", "2(5 - x) = 10 - 2x", "-4(1 + x) = -4 - 4x"] },
        { tipo: "ejemplo", titulo: "Ecuación con paréntesis", texto: "Resuelve: 3(x - 2) = 15", pasos: ["Distribuimos: 3x - 6 = 15", "Sumamos 6 a ambos lados: 3x = 21", "Dividimos entre 3: x = 7", "Verificamos: 3(7-2) = 3(5) = 15 ✓"] },
        { tipo: "concepto", titulo: "Paréntesis en ambos lados", texto: "Cuando hay paréntesis en ambos lados, distribuye primero en cada lado, luego agrupa términos semejantes.", subItems: ["4(x - 3) = 2(x + 4)", "Primero distribuir: 4x - 12 = 2x + 8", "Luego agrupar"] },
        { tipo: "ejemplo", titulo: "Compleja paso a paso", texto: "Resuelve: 4(x - 3) = 2(x + 4)", pasos: ["Distribuimos lado izquierdo: 4x - 12", "Distribuimos lado derecho: 2x + 8", "Igualamos: 4x - 12 = 2x + 8", "2x = 20 → x = 10"] },
        { tipo: "formula", formula: "a(b+c) = ab + ac", descripcion: "Propiedad distributiva: la herramienta clave para resolver ecuaciones con paréntesis." },
        { tipo: "ejemplo", titulo: "Ecuación fraccionaria simple", texto: "Resuelve: (2x + 1)/3 = 5", pasos: ["Multiplicamos ambos lados por 3", "2x + 1 = 15", "Restamos 1: 2x = 14", "Dividimos: x = 7"] },
        { tipo: "tabla", titulo: "Distributividad rápida", fila: [["3(x+2)", "3x+6"], ["2(x-5)", "2x-10"], ["-1(x+3)", "-x-3"], ["4(2x-1)", "8x-4"]] },
        { tipo: "resumen", items: ["Distributiva: a(b+c) = ab + ac", "Primero eliminar paréntesis", "Luego agrupar términos semejantes", "Despejar la variable paso a paso", "Siempre verificar al final"] },
        { tipo: "tip", texto: "Consejo: Cuando veas paréntesis, piensa distributiva primero. No intentes saltar pasos." },
      ],
    },
    dificil: {
      titulo: "Ecuaciones Complejas",
      contenido: [
        { tipo: "intro", texto: "Las ecuaciones complejas requieren múltiples técnicas: distribuir, agrupar, eliminar fracciones y manejar valor absoluto." },
        { tipo: "concepto", titulo: "Ecuaciones con fracciones", texto: "Cuando la ecuación tiene fracciones, multiplica toda la ecuación por el MCM de los denominadores para eliminarlas.", subItems: ["Identifica todos los denominadores", "Calcula el MCM", "Multiplica cada término por el MCM"] },
        { tipo: "ejemplo", titulo: "Eliminando fracciones", texto: "Resuelve: 2x/3 + x/6 = 5", pasos: ["MCM de 3 y 6 = 6", "Multiplicamos todo por 6: 4x + x = 30", "5x = 30", "x = 6"] },
        { tipo: "concepto", titulo: "Valor absoluto", texto: "El valor absoluto |a| es la distancia de 'a' a cero. |2x - 5| = 9 significa que 2x-5 puede ser 9 o -9.", subItems: ["|x| = a implica x = a o x = -a", "|x| < a implica -a < x < a", "|x| > a implica x > a o x < -a"] },
        { tipo: "ejemplo", titulo: "Ecuación con valor absoluto", texto: "Resuelve: |2x - 5| = 9", pasos: ["Caso 1: 2x - 5 = 9 → 2x = 14 → x = 7", "Caso 2: 2x - 5 = -9 → 2x = -4 → x = -2", "Soluciones: x = 7 o x = -2", "Verificación: |14-5|=9 ✓ y |-4-5|=9 ✓"] },
        { tipo: "formula", formula: "|ax + b| = c → ax+b = c  o  ax+b = −c", descripcion: "Para valor absoluto igual a un positivo, se generan dos ecuaciones." },
        { tipo: "ejemplo", titulo: "Ecuación con múltiples pasos", texto: "Resuelve: 3(2x - 1) - 4 = 2(x + 5)", pasos: ["Distribuimos: 6x - 3 - 4 = 2x + 10", "Simplificamos: 6x - 7 = 2x + 10", "Restamos 2x: 4x - 7 = 10", "Sumamos 7: 4x = 17 → x = 4.25"] },
        { tipo: "tabla", titulo: "Tipos de ecuaciones", fila: [["ax+b=c", "Primer grado simple"], ["a(x+b)=c", "Con paréntesis"], ["(ax+b)/d=c", "Con fracciones"], ["|ax+b|=c", "Con valor absoluto"]] },
        { tipo: "resumen", items: ["Fracciones → multiplicar por MCM", "|ax+b|=c → dos ecuaciones", "Paréntesis → distributiva primero", "Múltiples pasos → paso a paso", "SIEMPRE verificar las soluciones"] },
        { tipo: "tip", texto: "Consejo: Las ecuaciones con valor absoluto siempre dan dos soluciones. No olvides verificar AMBAS en la ecuación original." },
      ],
    },
  },
  inecuaciones: {
    facil: {
      titulo: "Inecuaciones Simples",
      contenido: [
        { tipo: "intro", texto: "Una inecuación es como una ecuación pero con signos de desigualdad: >, <, ≥ o ≤. Se resuelven igual que las ecuaciones, con una regla especial." },
        { tipo: "concepto", titulo: "Signos de inecuación", texto: "Los signos de desigualdad compara dos cantidades. > es mayor que, < es menor que, ≥ es mayor o igual, ≤ es menor o igual.", subItems: ["5 > 3 (5 es mayor que 3)", "2 < 7 (2 es menor que 7)", "4 ≥ 4 (4 es mayor o igual a 4)", "3 ≤ 10 (3 es menor o igual a 10)"] },
        { tipo: "ejemplo", titulo: "Inecuación simple", texto: "Resuelve: x + 3 > 7", pasos: ["Restamos 3 de ambos lados", "x > 4", "Solución: cualquier número mayor que 4", "En la recta numérica: círculo abierto en 4, sombra a la derecha"] },
        { tipo: "concepto", titulo: "Regla de oro", texto: "Si multiplicas o divides ambos lados por un número negativo, DEBES invertir el sentido de la inecuación.", subItems: ["Si a > b y c < 0, entonces ac < bc", "Si a < b y c < 0, entonces ac > bc", "Ejemplo: -2x < 6 → x > -3 (invertimos)"] },
        { tipo: "ejemplo", titulo: "Multiplicación negativa", texto: "Resuelve: -2x + 6 < 10", pasos: ["Restamos 6: -2x < 4", "Dividimos entre -2 (¡invertimos!)", "x > -2 (el < se convierte en >)", "Solución: x mayor que -2"] },
        { tipo: "formula", formula: "Si a > b y c > 0: ac > bc\nSi a > b y c < 0: ac < bc", descripcion: "Regla fundamental: invertir al multiplicar/dividir por negativo." },
        { tipo: "tabla", titulo: "Recta numérica", fila: [["x > 4", "○──────→ (abierto en 4)"], ["x ≥ 4", "●──────→ (cerrado en 4)"], ["x < 4", "←──────○ (abierto en 4)"], ["x ≤ 4", "←──────● (cerrado en 4)"]] },
        { tipo: "resumen", items: ["Las inecuaciones usan >, <, ≥, ≤", "Se resuelven igual que ecuaciones", "EXCEPTO al multiplicar/dividir por negativo", "Círculo abierto para > o <", "Círculo cerrado para ≥ o ≤"] },
        { tipo: "tip", texto: "Consejo: Al graficar en la recta numérica, círculo abierto (○) para sin igualdad, cerrado (●) para con igualdad." },
      ],
    },
    medio: {
      titulo: "Inecuaciones Compuestas",
      contenido: [
        { tipo: "intro", texto: "Las inecuaciones compuestas incluyen paréntesis, x en ambos lados y operaciones que requieren cuidado especial." },
        { tipo: "concepto", titulo: "Distribuir y resolver", texto: "Primero eliminamos paréntesis con distributiva, luego agrupamos términos semejantes y finalmente despejamos.", subItems: ["Distribuir: a(b+c) = ab + ac", "Agrupar: juntar x de un lado, números del otro", "Despejar: dejar x solo"] },
        { tipo: "ejemplo", titulo: "Inecuación con paréntesis", texto: "Resuelve: 2(x + 1) ≤ 12", pasos: ["Distribuimos: 2x + 2 ≤ 12", "Restamos 2: 2x ≤ 10", "Dividimos entre 2: x ≤ 5", "Solución: x menor o igual a 5"] },
        { tipo: "ejemplo", titulo: "x en ambos lados", texto: "Resuelve: 5x + 2 ≥ 3x + 8", pasos: ["Restamos 3x: 2x + 2 ≥ 8", "Restamos 2: 2x ≥ 6", "Dividimos entre 2: x ≥ 3", "Solución: x mayor o igual a 3"] },
        { tipo: "ejemplo", titulo: "Negativo en la ecuación", texto: "Resuelve: -2x + 6 < 10", pasos: ["Restamos 6: -2x < 4", "Dividimos entre -2 (invertimos)", "x > -2 (el < se convierte en >)", "Círculo abierto en -2, sombra a la derecha"] },
        { tipo: "formula", formula: "ax + b > cx + d → (a-c)x > d-b", descripcion: "Cuando hay x en ambos lados, junta todos los x de un lado." },
        { tipo: "resumen", items: ["Distribuir paréntesis primero", "Juntar x de un lado, números del otro", "Invertir si divides/multiplicas por negativo", "Verificar con un valor dentro y fuera del rango"] },
        { tipo: "tip", texto: "Consejo: Siempre verifica probando un valor que esté en tu solución y uno que no. Ambos deben cumplir o contradecir la inecuación." },
      ],
    },
    dificil: {
      titulo: "Inecuaciones con Valor Absoluto",
      contenido: [
        { tipo: "intro", texto: "Las inecuaciones con valor absoluto definen rangos de valores. Se resuelven separando en dos casos según la definición de valor absoluto." },
        { tipo: "concepto", titulo: "|x| < a significa -a < x < a", texto: "Cuando el valor absoluto es menor que un número positivo, la solución es un intervalo entre -a y a.", subItems: ["|x| < 5 → -5 < x < 5", "|x| < 10 → -10 < x < 10", "Siempre dos desigualdades conectadas"] },
        { tipo: "ejemplo", titulo: "Resolución paso a paso", texto: "Resuelve: |x - 3| < 5", pasos: ["Aplicamos la regla: -5 < x-3 < 5", "Sumamos 3 a todas las partes", "-5+3 < x < 5+3", "Resultado: -2 < x < 8"] },
        { tipo: "concepto", titulo: "|x| ≤ a significa -a ≤ x ≤ a", texto: "Similar al caso anterior pero incluye los extremos del intervalo.", subItems: ["|x| ≤ 4 → -4 ≤ x ≤ 4", "En la recta: ambos puntos cerrados (●)"] },
        { tipo: "ejemplo", titulo: "Con coeficiente", texto: "Resuelve: |2x + 1| ≤ 7", pasos: ["-7 ≤ 2x+1 ≤ 7", "Restamos 1: -8 ≤ 2x ≤ 6", "Dividimos entre 2: -4 ≤ x ≤ 3", "Solución: x entre -4 y 3, incluyendo extremos"] },
        { tipo: "formula", formula: "|ax+b| ≤ c → -c ≤ ax+b ≤ c", descripcion: "Para ≤ o <, se resuelve como doble inecuación encadenada." },
        { tipo: "formula", formula: "|ax+b| > c → ax+b > c  o  ax+b < -c", descripcion: "Para > o ≥, se separa en dos inecuaciones separadas." },
        { tipo: "ejemplo", titulo: "Mayor que (separado)", texto: "Resuelve: |x - 3| > 5", pasos: ["Caso 1: x-3 > 5 → x > 8", "Caso 2: x-3 < -5 → x < -2", "Solución: x < -2 o x > 8", "Dos intervalos separados en la recta"] },
        { tipo: "resumen", items: ["|ax+b| ≤ c → doble inecuación encadenada", "|ax+b| > c → dos inecuaciones separadas", "Siempre considerar los dos casos", "Verificar con valores de ambos intervalos"] },
        { tipo: "tip", texto: "Consejo: Dibuja SIEMPRE la recta numérica. Las inecuaciones con valor absoluto se ven mucho más claras con un diagrama." },
      ],
    },
  },
  geometria: {
    facil: {
      titulo: "Figuras y Medidas Básicas",
      contenido: [
        { tipo: "intro", texto: "La geometría estudia las formas, tamaños y propiedades del espacio. Conocer las figuras básicas es fundamental para el día a día." },
        { tipo: "concepto", titulo: "El triángulo", texto: "El triángulo tiene 3 lados y 3 ángulos. La suma de sus ángulos internos SIEMPRE es 180°.", subItems: ["Equilátero: 3 lados iguales", "Isósceles: 2 lados iguales", "Escaleno: 3 lados diferentes"] },
        { tipo: "formula", formula: "Área del triángulo = (base × altura) / 2", descripcion: "La base es cualquier lado, la altura es la perpendicular desde el lado opuesto." },
        { tipo: "ejemplo", titulo: "Área de un triángulo", texto: "Triángulo con base 10 cm y altura 6 cm:", pasos: ["Área = (10 × 6) / 2", "Área = 60 / 2 = 30 cm²", "El área siempre se mide en unidades cuadradas"] },
        { tipo: "concepto", titulo: "Cuadrado y rectángulo", texto: "Cuadrado: todos los lados iguales. Rectángulo: lados opuestos iguales.", subItems: ["Cuadrado: área = lado²", "Rectángulo: área = largo × ancho", "Perímetro = suma de todos los lados"] },
        { tipo: "ejemplo", titulo: "Área del cuadrado", texto: "Cuadrado de lado 5 cm:", pasos: ["Área = 5² = 25 cm²", "Perímetro = 4 × 5 = 20 cm", "Diferencia: área mide superficie, perímetro mide contorno"] },
        { tipo: "formula", formula: "Círculo: Área = πr²   Perímetro = 2πr", descripcion: "Donde r es el radio (distancia del centro al borde)." },
        { tipo: "ejemplo", titulo: "Círculo práctico", texto: "Un jardín circular con radio 7 metros:", pasos: ["Área = π × 7² = 49π ≈ 153.94 m²", "Perímetro = 2 × π × 7 = 14π ≈ 43.98 m", "π ≈ 3.1416"] },
        { tipo: "tabla", titulo: "Fórmulas rápidas", fila: [["Triángulo", "(b×h)/2"], ["Cuadrado", "l²"], ["Rectángulo", "l×a"], ["Círculo", "πr²"], ["Perímetro cuadrado", "4l"]] },
        { tipo: "resumen", items: ["Triángulo: ángulos suman 180°", "Área = superficie, Perímetro = contorno", "Cuadrado: lado², Rectángulo: largo×ancho", "Círculo: πr², Perímetro: 2πr", "Siempre con unidades correctas (cm², m²)"] },
        { tipo: "tip", texto: "Consejo: Dibuja SIEMPRE la figura con sus medidas antes de calcular. Visualizar ayuda mucho a evitar errores." },
      ],
    },
    medio: {
      titulo: "Pitágoras y Volúmenes",
      contenido: [
        { tipo: "intro", texto: "El teorema de Pitágoras es la herramienta más poderosa de la geometría para triángulos rectángulos. Los volúmenes miden el espacio de sólidos tridimensionales." },
        { tipo: "formula", formula: "a² + b² = c²", descripcion: "Pitágoras: en un triángulo rectángulo, la suma de los catetos al cuadrado es igual a la hipotenusa al cuadrado." },
        { tipo: "concepto", titulo: "Pitágoras explicado", texto: "En un triángulo rectángulo, el lado más largo (hipotenusa) se relaciona con los otros dos por esta fórmula.", subItems: ["Catetos: los dos lados que forman el ángulo recto", "Hipotenusa: el lado opuesto al ángulo recto (el más largo)", "Siempre: c² = a² + b²"] },
        { tipo: "ejemplo", titulo: "Pitágoras paso a paso", texto: "Triángulo con catetos 3 y 4:", pasos: ["c² = 3² + 4²", "c² = 9 + 16 = 25", "c = √25 = 5", "Hipotenusa = 5 unidades"] },
        { tipo: "concepto", titulo: "Volúmenes de sólidos", texto: "El volumen mide cuánto espacio ocupa un objeto tridimensional. Se mide en unidades cúbicas (cm³, m³).", subItems: ["Cubo: V = lado³", "Cilindro: V = πr²h", "Cono: V = (1/3)πr²h", "Esfera: V = (4/3)πr³"] },
        { tipo: "ejemplo", titulo: "Volumen del cubo", texto: "Cubo de lado 4 cm:", pasos: ["V = 4³ = 4×4×4", "V = 64 cm³", "Nota: cm³ porque es volumen (3 dimensiones)"] },
        { tipo: "ejemplo", titulo: "Volumen del cilindro", texto: "Cilindro con r=3 cm y h=10 cm:", pasos: ["V = π × 3² × 10", "V = π × 9 × 10", "V = 90π ≈ 282.74 cm³"] },
        { tipo: "tabla", titulo: "Volúmenes comunes", fila: [["Cubo", "l³"], ["Cilindro", "πr²h"], ["Cono", "(1/3)πr²h"], ["Esfera", "(4/3)πr³"]] },
        { tipo: "resumen", items: ["Pitágoras: a²+b²=c² (triángulo rectángulo)", "Hipotenusa SIEMPRE es c", "Volumen se mide en cm³ o m³", "Cubo=l³, Cilindro=πr²h, Cono=(1/3)πr²h"] },
        { tipo: "tip", texto: "Consejo: Para recordar Pitágoras, dibuja un cuadrado sobre cada lado del triángulo. El área del cuadrado grande = suma de los otros dos." },
      ],
    },
    dificil: {
      titulo: "Sólidos y Superficies",
      contenido: [
        { tipo: "intro", texto: "Los sólidos tridimensionales tienen volumen Y superficie. Calcular la superficie total de un sólido requiere sumar el área de todas sus caras." },
        { tipo: "concepto", titulo: "Superficie del cilindro", texto: "La superficie total del cilindro incluye las dos tapas circulares y la superficie lateral (como una etiqueta de lata).", subItems: ["2 círculos: 2 × πr²", "Superficie lateral: 2πrh", "Total: 2πr² + 2πrh = 2πr(r+h)"] },
        { tipo: "formula", formula: "ST cilindro = 2πr(r + h)", descripcion: "Superficie total = 2 círculos base + superficie lateral." },
        { tipo: "ejemplo", titulo: "Superficie del cilindro", texto: "Cilindro con r=3, h=10:", pasos: ["ST = 2π×3(3+10)", "ST = 6π×13 = 78π", "ST ≈ 245.04 cm²"] },
        { tipo: "concepto", titulo: "Volumen del cono", texto: "El volumen del cono es exactamente un tercio del cilindro con las mismas dimensiones.", subItems: ["V = (1/3)πr²h", "Un cono cabe 3 veces en un cilindro del mismo tamaño", "Es como una pirámide circular"] },
        { tipo: "ejemplo", titulo: "Volumen del cono", texto: "Cono con r=5, h=12:", pasos: ["V = (1/3)π(5²)(12)", "V = (1/3)π(25)(12)", "V = (1/3)(300π) = 100π ≈ 314.16 cm³"] },
        { tipo: "concepto", titulo: "Esfera", texto: "La esfera es el sólido más perfecto. Su superficie y volumen dependen solo del radio.", subItems: ["Superficie: SE = 4πr²", "Volumen: V = (4/3)πr³", "Es la figura que menos superficie tiene para un volumen dado"] },
        { tipo: "formula", formula: "Esfera: SE = 4πr², V = (4/3)πr³", descripcion: "Fórmulas de la esfera: superficie y volumen." },
        { tipo: "ejemplo", titulo: "Esfera completa", texto: "Esfera con radio 6:", pasos: ["SE = 4π(6²) = 4π×36 = 144π ≈ 452.39 cm²", "V = (4/3)π(6³) = (4/3)π×216 = 288π ≈ 904.78 cm³"] },
        { tipo: "tabla", titulo: "Superficies y volúmenes", fila: [["Cilindro", "2πr(r+h)", "πr²h"], ["Cono", "πr(r+√(r²+h²))", "(1/3)πr²h"], ["Esfera", "4πr²", "(4/3)πr³"]] },
        { tipo: "resumen", items: ["Superficie = área de todas las caras", "Superficie en cm², Volumen en cm³", "Cilindro: 2πr(r+h) superficie, πr²h volumen", "Cono: (1/3) del cilindro", "Esfera: 4πr² superficie, (4/3)πr³ volumen"] },
        { tipo: "tip", texto: "Consejo: Memoriza que el cono y la pirámide son 1/3 de su prisma/cilindro correspondiente. Es un patrón que siempre se cumple." },
      ],
    },
  },
  trigonometria: {
    facil: {
      titulo: "Razones Trigonométricas",
      contenido: [
        { tipo: "intro", texto: "La trigonometría estudia las relaciones entre los ángulos y los lados de los triángulos rectángulos. Las tres razones principales son sen, cos y tan." },
        { tipo: "concepto", titulo: "Seno (sen)", texto: "El seno de un ángulo es la razón entre el cateto opuesto y la hipotenusa.", subItems: ["sen(θ) = Opuesto / Hipotenusa", "sen(30°) = 1/2 = 0.5", "sen(45°) = √2/2 ≈ 0.707", "sen(60°) = √3/2 ≈ 0.866"] },
        { tipo: "concepto", titulo: "Coseno (cos)", texto: "El coseno es la razón entre el cateto adyacente y la hipotenusa.", subItems: ["cos(θ) = Adyacente / Hipotenusa", "cos(0°) = 1", "cos(30°) = √3/2 ≈ 0.866", "cos(60°) = 1/2 = 0.5"] },
        { tipo: "concepto", titulo: "Tangente (tan)", texto: "La tangente es la razón entre el cateto opuesto y el adyacente.", subItems: ["tan(θ) = Opuesto / Adyacente", "tan(45°) = 1", "tan(30°) = 1/√3 ≈ 0.577", "tan(60°) = √3 ≈ 1.732"] },
        { tipo: "formula", formula: "SOH-CAH-TOA", descripcion: "Sen=Opuesto/Hip, Cos=Adyacente/Hip, Tan=Opuesto/Adyacente. ¡Memoriza esto!" },
        { tipo: "ejemplo", titulo: "Ejemplo práctico", texto: "Triángulo con ángulo 30°, hipotenusa 10:", pasos: ["Cateto opuesto = 10 × sen(30°) = 10 × 0.5 = 5", "Cateto adyacente = 10 × cos(30°) = 10 × 0.866 = 8.66", "Tangente: tan(30°) = 5/8.66 ≈ 0.577"] },
        { tipo: "tabla", titulo: "Valores especiales", fila: [["30°", "sen=1/2, cos=√3/2, tan=1/√3"], ["45°", "sen=√2/2, cos=√2/2, tan=1"], ["60°", "sen=√3/2, cos=1/2, tan=√3"], ["90°", "sen=1, cos=0, tan=∞"]] },
        { tipo: "resumen", items: ["sen = Opuesto / Hipotenusa", "cos = Adyacente / Hipotenusa", "tan = Opuesto / Adyacente", "SOH-CAH-TOA para recordar", "Memoriza valores de 30°, 45°, 60°"] },
        { tipo: "tip", texto: "Consejo: SOH-CAH-TOA escrito fonéticamente suena como 'so-ka-toa'. ¡Úsalo como truco de memoria!" },
      ],
    },
    medio: {
      titulo: "Identidades y Aplicaciones",
      contenido: [
        { tipo: "intro", texto: "Las identidades trigonométricas son igualdades que siempre se cumplen. Son herramientas poderosas para simplificar expresiones y resolver problemas." },
        { tipo: "formula", formula: "sen²(x) + cos²(x) = 1", descripcion: "La identidad pitagórica: la más importante de la trigonometría." },
        { tipo: "ejemplo", titulo: "Uso de la identidad", texto: "Si sen(x) = 0.6, ¿cuánto es cos(x)?", pasos: ["0.6² + cos²(x) = 1", "0.36 + cos²(x) = 1", "cos²(x) = 0.64", "cos(x) = 0.8 (siendo x ángulo agudo)"] },
        { tipo: "concepto", titulo: "Relaciones entre razones", texto: "Las tres razones están conectadas entre sí. Si conoces dos, puedes encontrar la tercera.", subItems: ["tan(x) = sen(x)/cos(x)", "sen(x) = cos(90° - x)", "cos(x) = sen(90° - x)"] },
        { tipo: "ejemplo", titulo: "Encontrando tangente", texto: "Si sen(x) = 3/5 y cos(x) = 4/5:", pasos: ["tan(x) = sen(x)/cos(x)", "tan(x) = (3/5)/(4/5)", "tan(x) = 3/4 = 0.75"] },
        { tipo: "concepto", titulo: "Triángulo completo", texto: "Conocer las razones permite resolver cualquier triángulo rectángulo completo.", subItems: ["Conoces un ángulo y un lado → resuelves todo", "Usa sen para el lado opuesto", "Usa cos para el lado adyacente"] },
        { tipo: "ejemplo", titulo: "Triángulo 5-12-13", texto: "Triángulo con catetos 5 y 12:", pasos: ["Hipotenusa = √(5²+12²) = √(25+144) = √169 = 13", "tan(θ) = 5/12 ≈ 0.417", "θ = arctan(0.417) ≈ 22.6°"] },
        { tipo: "tabla", titulo: "Identidades útiles", fila: [["sen²+cos²=1", "Identidad pitagórica"], ["tan=sen/cos", "Relación fundamental"], ["sen(90-x)=cos", "Complementos"], ["1+tan²=sec²", "Identidad pitagórica 2"]] },
        { tipo: "resumen", items: ["sen²(x)+cos²(x)=1 siempre", "tan(x)=sen(x)/cos(x)", "sen(90°-x)=cos(x)", "Conoces 2 razones → hallas la 3ª", "Usa identidades para simplificar"] },
        { tipo: "tip", texto: "Consejo: Las tablas de valores especiales (30°, 45°, 60°) son esenciales. Memorízalas y la trigonometría será mucho más fácil." },
      ],
    },
    dificil: {
      titulo: "Trigonometría Avanzada",
      contenido: [
        { tipo: "intro", texto: "La trigonometría avanzada maneja ángulos fuera del primer cuadrante, identidades complejas y ecuaciones trigonométricas." },
        { tipo: "concepto", titulo: "Cuadrantes de la circunferencia", texto: "Los ángulos se miden desde el eje positivo en sentido antihorario. Cada cuadrante tiene signos diferentes para sen, cos y tan.", subItems: ["1er cuadrante (0°-90°): todos positivos", "2do cuadrante (90°-180°): solo sen positivo", "3er cuadrante (180°-270°): solo tan positivo", "4to cuadrante (270°-360°): solo cos positivo"] },
        { tipo: "formula", formula: "sen(180° - x) = sen(x)\ncos(180° - x) = -cos(x)", descripcion: "Para ángulos en el segundo cuadrante: sen se mantiene, cos cambia de signo." },
        { tipo: "ejemplo", titulo: "Ángulo en 2do cuadrante", texto: "Calcular sen(150°):", pasos: ["150° = 180° - 30°", "sen(150°) = sen(180° - 30°) = sen(30°)", "sen(150°) = 1/2", "En el 2do cuadrante, sen es positivo ✓"] },
        { tipo: "concepto", titulo: "Ángulos negativos y mayores", texto: "Para ángulos negativos y mayores a 360°, usamos equivalencias.", subItems: ["sen(-x) = -sen(x) (奇)", "cos(-x) = cos(x) (偶)", "Para >360°: resta 360° repetidamente"] },
        { tipo: "ejemplo", titulo: "Ecuación trigonométrica", texto: "Resuelve: 2sen(x) = 1, con 0° ≤ x ≤ 180°", pasos: ["sen(x) = 1/2 = 0.5", "x = 30° (1er cuadrante)", "x = 150° (2do cuadrante: 180°-30°)", "Soluciones: x = 30° y x = 150°"] },
        { tipo: "ejemplo", titulo: "Verificación con Pitágoras", texto: "Triángulo con lados 7, 24 y 25:", pasos: ["Verificamos: 7² + 24² = 49 + 576 = 625", "25² = 625 ✓ → es rectángulo", "sen(θ) = 7/25 = 0.28", "θ = arcsen(0.28) ≈ 16.26°"] },
        { tipo: "tabla", titulo: "Signos por cuadrante (ASTC)", fila: [["1er (0-90°)", "A: Todos (+)"], ["2do (90-180°)", "S: Solo sen (+)"], ["3er (180-270°)", "T: Solo tan (+)"], ["4to (270-360°)", "C: Solo cos (+)"]] },
        { tipo: "resumen", items: ["ASTC: All-Sin-Tan-Cos por cuadrante", "sen(180°-x)=sen(x), cos(180°-x)=-cos(x)", "sen(-x)=-sen(x), cos(-x)=cos(x)", "Ecuaciones trigonométricas pueden tener múltiples soluciones", "Siempre verificar con la identidad pitagórica"] },
        { tipo: "tip", texto: "Consejo: Dibuja la circunferencia trigonométrica y marca los cuadrantes con ASTC. Es la mejor referencia para no perder el signo." },
      ],
    },
  },
  estadistica: {
    facil: {
      titulo: "Medidas de Tendencia Central",
      contenido: [
        { tipo: "intro", texto: "La estadística nos ayuda a organizar y analizar datos. Las medidas de tendencia central nos dan una idea del 'centro' de un conjunto de datos." },
        { tipo: "concepto", titulo: "Media (promedio)", texto: "La media es la suma de todos los datos dividida entre la cantidad de datos. Es la medida más común.", subItems: ["Media = (suma de datos) / cantidad", "Ej: (2+4+6+8+10)/5 = 30/5 = 6", "Sensible a valores extremos"] },
        { tipo: "ejemplo", titulo: "Calcular la media", texto: "Notas de un estudiante: 8, 7, 9, 10, 6:", pasos: ["Suma: 8+7+9+10+6 = 40", "Cantidad: 5 notas", "Media: 40/5 = 8", "Su promedio es 8"] },
        { tipo: "concepto", titulo: "Mediana", texto: "La mediana es el valor que queda en el centro cuando los datos están ordenados de menor a mayor.", subItems: ["Ordena los datos de menor a mayor", "Si hay cantidad impar → el del medio", "Si hay cantidad par → promedio de los 2 centrales"] },
        { tipo: "ejemplo", titulo: "Calcular la mediana", texto: "Datos: 1, 3, 5, 7, 9:", pasos: ["Ya están ordenados", "Cantidad impar (5), la mediana es el dato 3", "Mediana = 5 (el valor central)"] },
        { tipo: "concepto", titulo: "Moda", texto: "La moda es el valor que MÁS se repite en los datos. Puede haber varias modas o ninguna.", subItems: ["3, 5, 3, 7, 3 → moda = 3 (se repite 3 veces)", "2, 4, 6, 8 → no hay moda", "1, 1, 2, 2 → hay dos modas: 1 y 2"] },
        { tipo: "ejemplo", titulo: "Ejemplo completo", texto: "Notas: 7, 8, 8, 9, 10:", pasos: ["Media: (7+8+8+9+10)/5 = 42/5 = 8.4", "Mediana: ordenados → 8 (dato central)", "Moda: 8 (se repite 2 veces)", "Todas medidas diferentes del mismo conjunto"] },
        { tipo: "tabla", titulo: "Comparación de medidas", fila: [["Media", "Promedio, sensible a extremos"], ["Mediana", "Valor central, resistente a extremos"], ["Moda", "Más frecuente, puede no existir"]] },
        { tipo: "resumen", items: ["Media = promedio (suma/cantidad)", "Mediana = valor central (ordenar)", "Moda = el que más se repite", "Puede haber varias modas o ninguna", "La mediana es mejor con datos atípicos"] },
        { tipo: "tip", texto: "Consejo: Si hay un dato muy alto o muy bajo (atípico), la media se distorsiona. Usa la mediana para representar mejor el centro." },
      ],
    },
    medio: {
      titulo: "Dispersión y Probabilidad",
      contenido: [
        { tipo: "intro", texto: "Mientras la tendencia central describe el 'centro' de los datos, la dispersión mide qué tan esparcidos están alrededor de ese centro." },
        { tipo: "concepto", titulo: "Varianza", texto: "La varianza es el promedio de las diferencias al cuadrado respecto a la media. Mide la dispersión promedio.", subItems: ["Varianza = Σ(xᵢ - media)² / n", "Mayor varianza = datos más esparcidos", "Varianza 0 = todos los datos iguales"] },
        { tipo: "formula", formula: "σ² = Σ(xᵢ - μ)² / N", descripcion: "Varianza poblacional: cada dato menos la media, al cuadrado, promediado." },
        { tipo: "ejemplo", titulo: "Calcular varianza", texto: "Datos: 4, 4, 4, 4 (todos iguales):", pasos: ["Media = 4", "Diferencias: 0, 0, 0, 0", "Diferencias al cuadrado: 0, 0, 0, 0", "Varianza = 0 (no hay dispersión)"] },
        { tipo: "concepto", titulo: "Desviación estándar", texto: "Es la raíz cuadrada de la varianza. Tiene las mismas unidades que los datos originales, lo que la hace más interpretable.", subItems: ["σ = √varianza", "Baja desviación = datos concentrados", "Alta desviación = datos esparcidos"] },
        { tipo: "ejemplo", titulo: "Desviación estándar", texto: "Varianza = 4, ¿desviación?", pasos: ["σ = √4 = 2", "Significa que los datos se desvían ~2 unidades de la media", "Si la media es 10, los datos están entre ~8 y ~12"] },
        { tipo: "concepto", titulo: "Probabilidad básica", texto: "La probabilidad mide la posibilidad de que ocurra un evento. Va de 0 (imposible) a 1 (seguro).", subItems: ["P(evento) = casos favorables / casos posibles", "P(dado 6) = 1/6 ≈ 0.167", "P(dado par) = 3/6 = 0.5"] },
        { tipo: "ejemplo", titulo: "Probabilidad práctica", texto: "En una bolsa hay 3 rojas y 7 azules. ¿Probabilidad de roja?", pasos: ["Casos favorables: 3 (rojas)", "Casos totales: 3+7 = 10", "P(roja) = 3/10 = 0.3 = 30%"] },
        { tipo: "tabla", titulo: "Escala de probabilidad", fila: [["0", "Imposible"], ["0.25", "Poco probable"], ["0.5", "Tan probable como no"], ["0.75", "Probable"], ["1", "Seguro"]] },
        { tipo: "resumen", items: ["Varianza = promedio de diferencias²", "Desviación estándar = √varianza", "P = casos favorables / casos totales", "Probabilidad va de 0 a 1", "Desviación alta = datos esparcidos"] },
        { tipo: "tip", texto: "Consejo: La desviación estándar te dice cuánto 'error promedio' tiene tu media. Una media de 8 con σ=0.5 es muy confiable." },
      ],
    },
    dificil: {
      titulo: "Probabilidad Avanzada y Combinatoria",
      contenido: [
        { tipo: "intro", texto: "La combinatoria cuenta cuántas posibilidades existen, y la probabilidad avanzada usa estas cuentas para calcular eventos complejos." },
        { tipo: "formula", formula: "C(n,k) = n! / (k!(n-k)!)", descripcion: "Combinaciones: importa el resultado, NO el orden de selección." },
        { tipo: "concepto", titulo: "Combinaciones vs Permutaciones", texto: "Combinaciones: el orden NO importa. Permutaciones: el orden SÍ importa.", subItems: ["C(10,3) = 120 combinaciones", "P(10,3) = 720 permutaciones", "P siempre es mayor o igual que C"] },
        { tipo: "ejemplo", titulo: "Combinaciones prácticas", texto: "¿Cuántas formas de elegir 3 personas de 10?", pasos: ["C(10,3) = 10! / (3! × 7!)", "= (10×9×8)/(3×2×1)", "= 720/6 = 120", "Hay 120 formas diferentes"] },
        { tipo: "formula", formula: "P(n,k) = n! / (n-k)!", descripcion: "Permutaciones: importa el orden de selección." },
        { tipo: "ejemplo", titulo: "Permutaciones", texto: "¿Cuántas formas de ordenar 5 de 3 objetos?", pasos: ["P(5,3) = 5! / (5-3)!", "= 120 / 2 = 60", "Hay 60 permutaciones de 3 entre 5"] },
        { tipo: "concepto", titulo: "Probabilidad conjunta", texto: "Para eventos independientes, la probabilidad de que ambos ocurran es el producto de cada probabilidad.", subItems: ["P(A∩B) = P(A) × P(B)", "P(tirar 2 dados = 6) = 1/6 × 1/6 = 1/36", "Solo funciona con eventos independientes"] },
        { tipo: "concepto", titulo: "Distribución normal", texto: "La distribución normal (campana de Gauss) es la más importante en estadística. Muchos fenómenos naturales la siguen.", subItems: ["68% de datos dentro de 1σ de la media", "95% dentro de 2σ", "99.7% dentro de 3σ (regla 68-95-99.7)"] },
        { tipo: "ejemplo", titulo: "Probabilidad con distribución", texto: "Alturas: μ=170cm, σ=10cm. ¿% entre 160 y 180?", pasos: ["160 = 170 - 10 = μ - σ", "180 = 170 + 10 = μ + σ", "Están dentro de 1σ de la media", "Por la regla 68-95-99.7: ~68%"] },
        { tipo: "tabla", titulo: "Regla 68-95-99.7", fila: [["μ ± 1σ", "~68% de los datos"], ["μ ± 2σ", "~95% de los datos"], ["μ ± 3σ", "~99.7% de los datos"]] },
        { tipo: "resumen", items: ["C(n,k) = combinaciones (sin orden)", "P(n,k) = permutaciones (con orden)", "P(A∩B) = P(A)×P(B) si independientes", "Normal: 68-95-99.7%", "Factorial: n! = n×(n-1)×...×1"] },
        { tipo: "tip", texto: "Consejo: Memoriza C(n,k) y P(n,k) como fórmulas base. Son la puerta de entrada a toda la combinatoria y probabilidad avanzada." },
      ],
    },
  },
};
