export default {
  aritmetica: {
    descripcion: "Domina las operaciones fundamentales: suma, resta, multiplicación, división, fracciones, porcentajes y propiedades numéricas.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Básico",
    temas: [
      "Operaciones básicas (suma, resta, multiplicación, división)",
      "Fracciones y decimales",
      "Porcentajes y reglas de tres",
      "Números primos y factores",
      "Potencias y raíces cuadradas",
    ],
  },
  algebra: {
    descripcion: "Aprende a trabajar con variables, expresiones algebraicas, ecuaciones de segundo grado y sistemas de ecuaciones.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Variables y expresiones algebraicas",
      "Factorización",
      "Ecuaciones de primer grado",
      "Ecuaciones de segundo grado",
      "Sistemas de ecuaciones",
    ],
  },
  ecuaciones: {
    descripcion: "Resuelve ecuaciones lineales con una incógnita aplicando propiedades de la igualdad y despejando la variable.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Ecuaciones de primer grado",
      "Propiedades de la igualdad",
      "Despeje de variables",
      "Ecuaciones con paréntesis",
      "Problemas aplicados",
    ],
  },
  inecuaciones: {
    descripcion: "Comprende y resuelve inecuaciones lineales, con valor absoluto y sistemas de inecuaciones.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Inecuaciones lineales simples",
      "Inecuaciones con paréntesis",
      "Inecuaciones con valor absoluto",
      "Representación en recta numérica",
      "Sistemas de inecuaciones",
    ],
  },
  geometria: {
    descripcion: "Explora figuras geométricas, áreas, perímetros, volúmenes y el teorema de Pitágoras.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Figuras planas y sus propiedades",
      "Área y perímetro",
      "Teorema de Pitágoras",
      "Volúmenes de sólidos",
      "Áreas de superficies",
    ],
  },
  trigonometria: {
    descripcion: "Estudia las razones trigonométricas, identidades fundamentales y aplicaciones en triángulos.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Avanzado",
    temas: [
      "Razones trigonométricas (sen, cos, tan)",
      "Circunferencia trigonométrica",
      "Identidades trigonométricas",
      "Resolución de triángulos",
      "Aplicaciones prácticas",
    ],
  },
  estadistica: {
    descripcion: "Aprende a analizar datos con media, mediana, moda, varianza, desviación estándar y probabilidad básica.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Media, mediana y moda",
      "Varianza y desviación estándar",
      "Probabilidad básica",
      "Combinaciones y permutaciones",
      "Distribución normal",
    ],
  },
  default: {
    descripcion: "Practica y refuerza tus conocimientos en este tema con cuestionarios personalizados.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: ["Conceptos básicos", "Práctica guiada", "Ejercicios aplicados"],
  },
};
