export default {
  aritmetica: {
    descripcion: "Domina las operaciones fundamentales: suma, resta, multiplicación, división, fracciones, porcentajes y propiedades numéricas.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Básico",
    temas: [
      "Operaciones básicas (suma, resta, multiplicación, división)",
      "Fracciones y decimales",
      "Porcentajes y reglas de tres",
      "Números primos y factores",
      "Potencias y raíces cuadradas",
    ],
  },
  algebra: {
    descripcion: "Aprende a trabajar con variables, expresiones algebraicas, ecuaciones de segundo grado y sistemas de ecuaciones.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Variables y expresiones algebraicas",
      "Factorización",
      "Ecuaciones de primer grado",
      "Ecuaciones de segundo grado",
      "Sistemas de ecuaciones",
    ],
  },
  ecuaciones: {
    descripcion: "Resuelve ecuaciones lineales con una incógnita aplicando propiedades de la igualdad y despejando la variable.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Ecuaciones de primer grado",
      "Propiedades de la igualdad",
      "Despeje de variables",
      "Ecuaciones con paréntesis",
      "Problemas aplicados",
    ],
  },
  inecuaciones: {
    descripcion: "Comprende y resuelve inecuaciones lineales, con valor absoluto y sistemas de inecuaciones.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Inecuaciones lineales simples",
      "Inecuaciones con paréntesis",
      "Inecuaciones con valor absoluto",
      "Representación en recta numérica",
      "Sistemas de inecuaciones",
    ],
  },
  geometria: {
    descripcion: "Explora figuras geométricas, áreas, perímetros, volúmenes y el teorema de Pitágoras.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Figuras planas y sus propiedades",
      "Área y perímetro",
      "Teorema de Pitágoras",
      "Volúmenes de sólidos",
      "Áreas de superficies",
    ],
  },
  trigonometria: {
    descripcion: "Estudia las razones trigonométricas, identidades fundamentales y aplicaciones en triángulos.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Avanzado",
    temas: [
      "Razones trigonométricas (sen, cos, tan)",
      "Circunferencia trigonométrica",
      "Identidades trigonométricas",
      "Resolución de triángulos",
      "Aplicaciones prácticas",
    ],
  },
  estadistica: {
    descripcion: "Aprende a analizar datos con media, mediana, moda, varianza, desviación estándar y probabilidad básica.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Media, mediana y moda",
      "Varianza y desviación estándar",
      "Probabilidad básica",
      "Combinaciones y permutaciones",
      "Distribución normal",
    ],
  },
  historia_peru: {
    descripcion: "Recorre la historia del Perú desde las civilizaciones preincaicas hasta la república, conociendo sus grandes protagonistas y acontecimientos.",
    lecciones: 6,
    preguntasEstimadas: 30,
    nivel: "Intermedio",
    temas: [
      "Civilizaciones preincaicas (Chavín, Nazca, Moche, Wari)",
      "El Imperio Inca: organización, economía y sociedad",
      "La conquista española",
      "La independencia del Perú",
      "La República: guerras, gobierno y transformaciones",
      "Historia contemporánea del Perú",
    ],
  },
  historia_universal: {
    descripcion: "Estudia los grandes acontecimientos de la historia mundial: desde las civilizaciones antiguas hasta los conflictos y transformaciones del siglo XX.",
    lecciones: 6,
    preguntasEstimadas: 30,
    nivel: "Intermedio",
    temas: [
      "Civilizaciones antiguas (Egipto, Grecia, Roma)",
      "Edad Media y feudalismo",
      "Renaissance y exploración",
      "Revoluciones políticas y sociales",
      "Guerras mundiales y Guerra Fría",
      "Mundo contemporáneo",
    ],
  },
  geografia_general: {
    descripcion: "Estudia la geografía del Perú y del mundo: regiones naturales, clima, población, recursos naturales y geografía económica.",
    lecciones: 6,
    preguntasEstimadas: 30,
    nivel: "Intermedio",
    temas: [
      "Geografía del Perú",
      "Clima y relieve",
      "Población y demografía",
      "Recursos naturales",
      "Geografía económica",
    ],
  },
  quimica_general: {
    descripcion: "Explora los fundamentos de la química: materia, elementos, tabla periódica, enlaces, reacciones y estoquiometría.",
    lecciones: 6,
    preguntasEstimadas: 30,
    nivel: "Intermedio",
    temas: [
      "Química general y materia",
      "Elementos y tabla periódica",
      "Enlaces químicos",
      "Reacciones químicas",
      "Estoquiometría",
    ],
  },
  civilizaciones_preincaicas: {
    descripcion: "Estudia las grandes civilizaciones que florecieron en el Perú antes de los incas: Chavín, Nazca, Moche, Chimú y sus logros en agricultura, metalurgia, textiles y arquitectura.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Civilizaciones Chavín, Nazca, Moche y Chimú",
      "Avances en agricultura, metalurgia, textiles y arquitectura",
      "Análisis cronológico y evidencia arqueológica",
    ],
  },
  imperio_incaico: {
    descripcion: "Conoce el Imperio Inca: su gobierno, economía, sistema de mit'a, quipus, red de caminos y la expansión bajo Pachacútec y Túpac Yupanqui.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "El Tahuantinsuyo: Cusco y los incas básicos",
      "Gobierno, mit'a, quipus y red vial inca",
      "Expansión bajo Pachacútec y Túpac Yupanqui",
    ],
  },
  conquista_colonia: {
    descripcion: "Analiza la conquista española del Perú, la sociedad colonial, el sistema de castas, la encomienda y la rebelión de Túpac Amaru II.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Pizarro, Atahualpa y la conquista del Perú",
      "Sociedad colonial, castas, encomienda y virreinato",
      "Rebelión de Túpac Amaru II y economía colonial",
    ],
  },
  guerra_del_pacifico: {
    descripcion: "Estudia la Guerra del Pacífico (1879-1884): sus causas por el salitre, las batallas clave, el Tratado de Ancón y las consecuencias a largo plazo para el Perú.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "La Guerra del participantes y fechas clave",
      "Batallas, Tratado de Ancón y pérdidas territoriales",
      "Causas del salitre, impacto económico y consecuencias",
    ],
  },
  revolucion_industrial: {
    descripcion: "Explora la Revolución Industrial: máquina de vapor, fábricas, cambios sociales, trabajo infantil, la segunda revolución industrial y su impacto global.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Máquina de vapor, fábricas y telar mecánico",
      "Condiciones laborales, trabajo infantil y movimientos obreros",
      "Karl Marx, segunda revolución industrial e imperialismo",
    ],
  },
  guerra_mundial_1: {
    descripcion: "Estudia la Primera Guerra Mundial (1914-1918): causas, la Triple Entente vs Triple Alianza, guerra de trincheras, el Tratado de Versalles y sus consecuencias.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Nacionalismo, imperialismo y sistema de alianzas",
      "Guerra de trincheras y batallas del Somme, Verdún, Gallípoli",
      "Tratado de Versalles y semillas de la Segunda Guerra Mundial",
    ],
  },
  guerra_mundial_2: {
    descripcion: "Comprende la Segunda Guerra Mundial (1939-1945): el Holocausto, las batallas decisivas, las bombas atómicas y los Juicios de Núremberg.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Hitler, el nazismo y la invasión de Polonia",
      "El Holocausto, Stalingrado y el Día D",
      "Bombas atómicas, Núremberg y el nuevo orden mundial",
    ],
  },
  guerra_franco_prusiana: {
    descripcion: "Analiza la Guerra Franco-Prusiana (1870-1871): Bismarck, la batalla de Sedán, la unificación de Alemania y el Tratado de Frankfurt.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Bismarck, Napoleón III y el detonante de la guerra",
      "La unificación de Alemania y el Tratado de Frankfurt",
      "Estrategia militar, diplomacia de Bismarck y revanchismo francés",
    ],
  },
  revolucion_rusa: {
    descripcion: "Estudia la Revolución Rusa (1917): la caída del zar, Lenin, los bolcheviques, la guerra civil, Stalin y la formación de la URSS.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Nicolás II, Revolución de Febrero y Lenin",
      "Guerra civil, comunismo de guerra y la NEP",
      "Marxismo-leninismo, Stalin y el totalitarismo soviético",
    ],
  },
  guerra_fria: {
    descripcion: "Comprende la Guerra Fría (1947-1991): la división del mundo, crisis de los misiles, carrera espacial, guerras proxy y la caída de la URSS.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "EE.UU. vs URSS: bloques capitalista y comunista",
      "Crisis de los misiles, Vietnam y carrera espacial",
      "Distensión, caída del Muro de Berlín y disolución de la URSS",
    ],
  },
  tabla_periodica: {
    descripcion: "Estudia la tabla periódica: organización de los elementos, grupos, períodos, tendencias periódicas, configuración electrónica y propiedades de los elementos.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Organización de la tabla periódica: períodos, grupos y bloques",
      "Configuración electrónica y estructura atómica",
      "Tendencias periódicas: radioiedad, energía de ionización, electronegatividad",
    ],
  },
  enlaces_quimicos: {
    descripcion: "Analiza los tipos de enlaces químicos: iónicos, covalentes y metálicos, así como la polaridad, la teoría VSEPR y la geometría molecular.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Enlace iónico: transferencia de electrones y energía reticular",
      "Enlace covalente: compartición de electrones y polaridad",
      "Teoría VSEPR y geometría molecular",
    ],
  },
  reacciones_quimicas: {
    descripcion: "Comprende los tipos de reacciones químicas, el balanceo de ecuaciones, la estequiometría y el reagente limitante.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Tipos de reacciones: síntesis, descomposición, combustión y sustitución",
      "Balanceo de ecuaciones químicas",
      "Estequiometría y reagente limitante",
    ],
  },
  acidos_bases: {
    descripcion: "Estudia los ácidos y bases: escala de pH, indicadores ácido-base, neutralización, amortiguadores (buffers) y valoraciones (titulaciones).",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Definiciones de ácidos y bases: Arrhenius, Brønsted-Lowry y Lewis",
      "Escala de pH, indicadores y neutralización",
      "Buffers (amortiguadores) y curvas de titulación",
    ],
  },
  quimica_organica: {
    descripcion: "Explora la química orgánica: hidrocarburos, grupos funcionales, isomería y polímeros, con aplicaciones en la vida cotidiana.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Hidrocarburos: alcanos, alquenos y alquinos",
      "Grupos funcionales: alcoholes, ácidos carboxílicos y aminas",
      "Isomería, polímeros y aplicaciones en la industria",
    ],
  },
  biologia_general: {
    descripcion: "Estudia los niveles de organización de la vida, la homeostasis, el método científico y las características fundamentales de los seres vivos.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Niveles de organización biológica",
      "Homeostasis y mantenimiento de la vida",
      "Método científico en biología",
      "Características de los seres vivos",
    ],
  },
  celulas: {
    descripcion: "Comprende la estructura y función de las células: procariontes vs eucariontes, organelos, membrana plasmática, fotosíntesis y respiración celular.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Células procariotas y eucariotas",
      "Organelos celulares y sus funciones",
      "Membrana plasmática y transporte",
      "Fotosíntesis y respiración celular",
    ],
  },
  genetica: {
    descripcion: "Aprende los principios de la herencia genética: leyes de Mendel, dominancia, cuadrados de Punnett, ADN, mutaciones y patrones de herencia.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Leyes de Mendel y genética básica",
      "Dominante, recesivo y cuadrados de Punnett",
      "ADN, genes y cromosomas",
      "Mutaciones y patrones de herencia",
    ],
  },
  ecologia: {
    descripcion: "Explora los ecosistemas, cadenas alimenticias, biomas, biodiversidad y los principales problemas ambientales que afectan al planeta.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Ecosistemas y sus componentes",
      "Cadenas y redes alimenticias",
      "Biomas terrestres y acuáticos",
      "Biodiversidad y problemas ambientales",
    ],
  },
  anatomia_humana: {
    descripcion: "Estudia los principales sistemas del cuerpo humano: esquelético, muscular, circulatorio, respiratorio y digestivo.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Sistema esquelético y óseo",
      "Sistema muscular",
      "Sistema circulatorio y cardíaco",
      "Sistema respiratorio y digestivo",
    ],
  },
  geografia_fisica: {
    descripcion: "Estudia los continentes, océanos, relieve terrestre, climas, placas tectónicas y los principales ríos del mundo.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Continentes y océanos del mundo",
      "Relieve terrestre y cordilleras",
      "Climas y clasificación climática",
      "Placas tectónicas y ríos principales",
    ],
  },
  geografia_peru: {
    descripcion: "Conoce las regiones del Perú, su clima, ríos, recursos naturales y la geografía de Lima y sus principales ciudades.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Regiones naturales del Perú",
      "Clima y ríos del Perú",
      "Recursos naturales y economía",
      "Geografía de Lima y ciudades principales",
    ],
  },
  ingles_basico: {
    descripcion: "Aprende vocabulario b�sico en ingl�s: saludos, n�meros, colores, y construye oraciones simples para comunicarte en situaciones cotidianas.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Basico",
    temas: [
      "Saludos y presentaciones",
      "Numeros y colores",
      "Vocabulario basico",
      "Oraciones simples",
      "Preguntas basicas"
    ],
  },
  ingles_gramatica: {
    descripcion: "Domina la gramatica inglesa: presente simple, pasado simple, futuro, articulos, preposiciones y estructura de oraciones.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Presente simple y continuo",
      "Pasado simple y perfecto",
      "Futuro con will y going to",
      "Articulos y preposiciones",
      "Estructura de oraciones"
    ],
  },
  ingles_verbos: {
    descripcion: "Aprende los verbos irregulares mas comunes en ingles, su conjugacion en todos los tiempos verbales y su uso en contexto.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Verbos irregulares comunes",
      "Conjugacion en presente",
      "Conjugacion en pasado",
      "Participios y perfectos",
      "Phrasal verbs basicos"
    ],
  },
  ingles_conversacion: {
    descripcion: "Practica conversaciones en ingles: presentaciones, pedir direcciones, ordenar comida, hacer compras y mantener dialogos cotidianos.",
    lecciones: 3,
    preguntasEstimadas: 15,
    nivel: "Intermedio",
    temas: [
      "Presentaciones personales",
      "Pedir direcciones",
      "Ordenar comida",
      "De compras",
      "Dialogos cotidianos"
    ],
  },
};