export default {
  aritmetica: {
    facil: [
      { question: "¿Cuánto es 24 ÷ 6?", options: ["3", "4", "6", "8"], correctIndex: 1 },
      { question: "¿Cuánto es 15 + 27?", options: ["32", "40", "42", "44"], correctIndex: 2 },
      { question: "¿Cuánto es 9 × 7?", options: ["56", "63", "72", "81"], correctIndex: 1 },
      { question: "¿Cuánto es 144 ÷ 12?", options: ["10", "11", "12", "14"], correctIndex: 2 },
      { question: "¿Cuánto es 58 - 23?", options: ["25", "35", "45", "33"], correctIndex: 1 },
    ],
    medio: [
      { question: "¿Cuál es el 20% de 150?", options: ["20", "25", "30", "35"], correctIndex: 2 },
      { question: "¿Cuánto es 3/4 + 1/2?", options: ["5/4", "4/4", "7/4", "1 1/4"], correctIndex: 2 },
      { question: "Si compras 3 articles a S/. 45.50 c/u, ¿cuánto pagas?", options: ["S/. 125.50", "S/. 135.50", "S/. 136.50", "S/. 140.00"], correctIndex: 2 },
      { question: "¿Cuánto es 2³ + 3²?", options: ["13", "15", "17", "19"], correctIndex: 2 },
      { question: "¿Cuál es el MCM de 6 y 8?", options: ["12", "24", "48", "36"], correctIndex: 1 },
    ],
    dificil: [
      { question: "¿Cuál de estos números es primo?", options: ["9", "15", "17", "21"], correctIndex: 2 },
      { question: "Resuelve: (2⁴ × 3²) ÷ 6", options: ["24", "36", "48", "72"], correctIndex: 0 },
      { question: "¿Cuánto es √(196) + √(81)?", options: ["20", "22", "26", "28"], correctIndex: 2 },
      { question: "Un número aumentado en un 50% da 180. ¿Cuál es el número?", options: ["90", "100", "120", "135"], correctIndex: 2 },
      { question: "¿Cuánto es 7! ÷ 5! ?", options: ["7", "12", "42", "21"], correctIndex: 2 },
    ],
  },
  algebra: {
    facil: [
      { question: "Si x + 5 = 12, ¿cuánto es x?", options: ["5", "6", "7", "8"], correctIndex: 2 },
      { question: "Simplifica: 3a + 2a", options: ["5a", "6a", "5a²", "3a²"], correctIndex: 0 },
      { question: "¿Cuánto es 2x cuando x = 6?", options: ["8", "10", "12", "14"], correctIndex: 2 },
      { question: "Si y - 3 = 10, ¿cuánto es y?", options: ["7", "10", "13", "30"], correctIndex: 2 },
      { question: "Simplifica: 5(x + 1)", options: ["5x + 1", "5x + 5", "5x + 6", "x + 5"], correctIndex: 1 },
    ],
    medio: [
      { question: "Resuelve: 2x + 3 = 15", options: ["x = 5", "x = 6", "x = 7", "x = 9"], correctIndex: 1 },
      { question: "Si 4a - 7 = 9, ¿cuánto es a?", options: ["2", "3", "4", "5"], correctIndex: 2 },
      { question: "Factoriza: x² - 9", options: ["(x-3)²", "(x+3)²", "(x-3)(x+3)", "(x-9)(x+1)"], correctIndex: 2 },
      { question: "Resuelve: 3(x - 2) = 21", options: ["x = 5", "x = 7", "x = 9", "x = 11"], correctIndex: 2 },
      { question: "¿Cuál es el valor de x si 5x/2 = 20?", options: ["4", "6", "8", "10"], correctIndex: 2 },
    ],
    dificil: [
      { question: "Resuelve el sistema: x + y = 10, x - y = 4", options: ["x=6, y=4", "x=7, y=3", "x=5, y=5", "x=8, y=2"], correctIndex: 1 },
      { question: "Si f(x) = 2x² - 3x + 1, ¿cuánto es f(2)?", options: ["1", "3", "5", "7"], correctIndex: 1 },
      { question: "Factoriza: x² + 5x + 6", options: ["(x+1)(x+6)", "(x+2)(x+3)", "(x-2)(x-3)", "(x+1)(x+5)"], correctIndex: 1 },
      { question: "Resuelve: x² - 5x + 6 = 0", options: ["x=1,6", "x=2,3", "x=-2,-3", "x=1,5"], correctIndex: 1 },
      { question: "Si 3^(x+1) = 27, ¿cuánto es x?", options: ["1", "2", "3", "4"], correctIndex: 1 },
    ],
  },
  ecuaciones: {
    facil: [
      { question: "Resuelve: x + 8 = 15", options: ["5", "6", "7", "8"], correctIndex: 2 },
      { question: "Resuelve: 2x = 18", options: ["6", "8", "9", "10"], correctIndex: 2 },
      { question: "Resuelve: x/3 = 9", options: ["3", "12", "18", "27"], correctIndex: 3 },
      { question: "Resuelve: x - 11 = 4", options: ["7", "11", "15", "19"], correctIndex: 2 },
      { question: "Resuelve: 5x + 5 = 20", options: ["2", "3", "4", "5"], correctIndex: 2 },
    ],
    medio: [
      { question: "Resuelve: 2x + 5 = 17", options: ["x = 5", "x = 6", "x = 7", "x = 8"], correctIndex: 1 },
      { question: "Resuelve: 3x - 4 = 11", options: ["x = 3", "x = 4", "x = 5", "x = 6"], correctIndex: 2 },
      { question: "Resuelve: x/4 = 9", options: ["x = 13", "x = 24", "x = 36", "x = 45"], correctIndex: 2 },
      { question: "Resuelve: 4(x - 3) = 20", options: ["x = 6", "x = 7", "x = 8", "x = 9"], correctIndex: 2 },
      { question: "Resuelve: (2x + 1)/3 = 5", options: ["x = 5", "x = 6", "x = 7", "x = 8"], correctIndex: 2 },
    ],
    dificil: [
      { question: "Resuelve: 3(2x - 1) - 4 = 2(x + 5)", options: ["x=3", "x=4", "x=5", "x=6"], correctIndex: 2 },
      { question: "Si 5x - 2(3x - 4) = 12, ¿x?", options: ["x = 2", "x = 4", "x = 6", "x = 8"], correctIndex: 1 },
      { question: "Resuelve: 2x/3 + x/6 = 5", options: ["x = 4", "x = 5", "x = 6", "x = 7"], correctIndex: 2 },
      { question: "Resuelve: |2x - 5| = 9", options: ["x=2,7", "x=-2,7", "x=1,8", "x=3,6"], correctIndex: 0 },
      { question: "Resuelve: (x+2)/2 - (x-1)/3 = 1", options: ["x=2", "x=4", "x=6", "x=8"], correctIndex: 1 },
    ],
  },
  inecuaciones: {
    facil: [
      { question: "¿Cuál es la solución de x + 3 > 7?", options: ["x > 3", "x > 4", "x > 7", "x > 10"], correctIndex: 1 },
      { question: "Resuelve: 2x < 10", options: ["x < 2", "x < 5", "x < 8", "x < 10"], correctIndex: 1 },
      { question: "Si x - 4 ≥ 1, ¿cuál es x?", options: ["x ≥ 3", "x ≥ 4", "x ≥ 5", "x ≥ 6"], correctIndex: 2 },
      { question: "Resuelve: 3x > 15", options: ["x > 3", "x > 4", "x > 5", "x > 6"], correctIndex: 2 },
      { question: "Resuelve: x + 10 ≤ 20", options: ["x ≤ 8", "x ≤ 10", "x ≤ 12", "x ≤ 15"], correctIndex: 1 },
    ],
    medio: [
      { question: "Resuelve: 3x - 5 > 10", options: ["x > 3", "x > 4", "x > 5", "x > 6"], correctIndex: 2 },
      { question: "Resuelve: 2(x + 1) ≤ 12", options: ["x ≤ 4", "x ≤ 5", "x ≤ 6", "x ≤ 7"], correctIndex: 1 },
      { question: "Resuelve: (x - 3)/2 > 4", options: ["x > 5", "x > 7", "x > 9", "x > 11"], correctIndex: 3 },
      { question: "Resuelve: 5x + 2 ≥ 3x + 8", options: ["x ≥ 1", "x ≥ 2", "x ≥ 3", "x ≥ 4"], correctIndex: 2 },
      { question: "Resuelve: -2x + 6 < 10", options: ["x > -2", "x > 2", "x < 2", "x < -2"], correctIndex: 0 },
    ],
    dificil: [
      { question: "Resuelve: |x - 3| < 5", options: ["-2 < x < 8", "-1 < x < 7", "0 < x < 6", "1 < x < 5"], correctIndex: 0 },
      { question: "Resuelve: 3x - 7 > 2x + 3", options: ["x > 3", "x > 5", "x > 7", "x > 10"], correctIndex: 3 },
      { question: "Resuelve: (2x+1)/3 ≥ (x-2)/2", options: ["x ≥ -7", "x ≥ 7", "x ≥ -5", "x ≥ 5"], correctIndex: 0 },
      { question: "Resuelve: 4 - 3x > -5", options: ["x < 3", "x < -3", "x > 3", "x > -3"], correctIndex: 0 },
      { question: "Resuelve: |2x + 1| ≤ 7", options: ["-4 ≤ x ≤ 3", "-3 ≤ x ≤ 4", "-5 ≤ x ≤ 2", "-2 ≤ x ≤ 5"], correctIndex: 0 },
    ],
  },
  geometria: {
    facil: [
      { question: "¿Cuánto mide la suma de ángulos internos de un triángulo?", options: ["90°", "180°", "270°", "360°"], correctIndex: 1 },
      { question: "¿Cuánto es el área de un cuadrado de lado 5 cm?", options: ["10 cm²", "15 cm²", "20 cm²", "25 cm²"], correctIndex: 3 },
      { question: "Un rectángulo tiene largo 8 y ancho 3. ¿Cuánto es su perímetro?", options: ["11", "22", "24", "26"], correctIndex: 2 },
      { question: "¿Cuántos lados tiene un hexágono?", options: ["5", "6", "7", "8"], correctIndex: 1 },
      { question: "¿Cuánto es el área de un triángulo con base 10 y altura 6?", options: ["16", "20", "30", "60"], correctIndex: 2 },
    ],
    medio: [
      { question: "¿Cuánto es la hipotenusa de un triángulo con catetos 3 y 4?", options: ["5", "6", "7", "12"], correctIndex: 0 },
      { question: "El área de un círculo es πr². Si r=7, ¿cuánto es el área?", options: ["49π", "98π", "147π", "196π"], correctIndex: 0 },
      { question: "¿Cuánto es el volumen de un cubo de lado 4 cm?", options: ["16 cm³", "32 cm³", "48 cm³", "64 cm³"], correctIndex: 3 },
      { question: "Un trapecio tiene bases 8 y 12, y altura 5. ¿Su área?", options: ["40", "50", "60", "80"], correctIndex: 1 },
      { question: "¿Cuánto mide cada ángulo interno de un hexágono regular?", options: ["100°", "120°", "135°", "150°"], correctIndex: 1 },
    ],
    dificil: [
      { question: "Un cilindro tiene r=3 y h=10. ¿Cuánto es su volumen?", options: ["30π", "60π", "90π", "180π"], correctIndex: 2 },
      { question: "¿Cuánto es el área de un círculo con diámetro 14?", options: ["49π", "98π", "196π", "28π"], correctIndex: 0 },
      { question: "Un cono tiene r=5 y h=12. ¿Cuánto es su volumen?", options: ["60π", "100π", "120π", "300π"], correctIndex: 1 },
      { question: "¿Cuánto es el área de una esfera con radio 6?", options: ["36π", "72π", "144π", "216π"], correctIndex: 2 },
      { question: "Un prisma rectangular tiene 5×3×4. ¿Cuánta es su superficie total?", options: ["47", "60", "94", "120"], correctIndex: 2 },
    ],
  },
  trigonometria: {
    facil: [
      { question: "¿Cuánto es sen(30°)?", options: ["1/2", "√2/2", "√3/2", "1"], correctIndex: 0 },
      { question: "¿Cuánto es cos(0°)?", options: ["0", "1/2", "√2/2", "1"], correctIndex: 3 },
      { question: "¿Cuánto es tan(45°)?", options: ["0", "1/2", "1", "√3"], correctIndex: 2 },
      { question: "En un triángulo rectángulo, sen = ?", options: ["Cateto adyacente / hipotenusa", "Cateto opuesto / hipotenusa", "Opuesto / adyacente", "Hipotenusa / opuesto"], correctIndex: 1 },
      { question: "¿Cuánto es cos(60°)?", options: ["0", "1/2", "√3/2", "1"], correctIndex: 1 },
    ],
    medio: [
      { question: "En un triángulo con ángulo 30° y hipotenusa 10, ¿cuánto mide el cateto opuesto?", options: ["3", "5", "6", "8"], correctIndex: 1 },
      { question: "¿Cuánto es sen²(x) + cos²(x)?", options: ["0", "1", "2", "Depende de x"], correctIndex: 1 },
      { question: "Si tan(θ) = 3/4, ¿cuánto es sen(θ)?", options: ["3/4", "3/5", "4/5", "4/3"], correctIndex: 1 },
      { question: "¿Cuánto es sen(90°)?", options: ["0", "1/2", "√2/2", "1"], correctIndex: 3 },
      { question: "Un triángulo tiene catetos 5 y 12. ¿Cuánto es tan del ángulo opuesto al cateto 5?", options: ["5/12", "12/5", "5/13", "12/13"], correctIndex: 0 },
    ],
    dificil: [
      { question: "¿Cuánto es sen(150°)?", options: ["-1/2", "1/2", "√3/2", "-√3/2"], correctIndex: 1 },
      { question: "Si sen(A) = 0.6 y A es agudo, ¿cuánto es cos(A)?", options: ["0.4", "0.6", "0.8", "1.0"], correctIndex: 2 },
      { question: "Resuelve: 2sen(x) = 1, donde 0° ≤ x ≤ 180°", options: ["30° y 150°", "30° y 60°", "60° y 120°", "45° y 135°"], correctIndex: 0 },
      { question: "¿Cuánto es tan(300°)?", options: ["-√3", "-1", "1", "√3"], correctIndex: 0 },
      { question: "En un triángulo con lados 7, 24 y 25, ¿cuánto es el ángulo mayor?", options: ["60°", "75°", "90°", "120°"], correctIndex: 2 },
    ],
  },
  estadistica: {
    facil: [
      { question: "¿Cuál es la media de 2, 4, 6, 8, 10?", options: ["4", "5", "6", "8"], correctIndex: 2 },
      { question: "¿Cuál es la moda de 3, 5, 3, 7, 3?", options: ["3", "5", "7", "4"], correctIndex: 0 },
      { question: "¿Cuál es la mediana de 1, 3, 5, 7, 9?", options: ["3", "5", "7", "9"], correctIndex: 1 },
      { question: "¿Cuántos datos hay en la muestra: 4, 8, 12, 16?", options: ["3", "4", "5", "6"], correctIndex: 1 },
      { question: "¿Cuál es la media de 10, 20, 30?", options: ["15", "20", "25", "30"], correctIndex: 1 },
    ],
    medio: [
      { question: "¿Cuál es la varianza de 2, 4, 6?", options: ["2", "3", "4", "8/3"], correctIndex: 3 },
      { question: "En una encuesta: A=30%, B=45%, C=25%. ¿Cuál es la moda?", options: ["A", "B", "C", "No hay moda"], correctIndex: 1 },
      { question: "Los datos: 3, 7, 8, 5, 12. ¿Cuál es la mediana?", options: ["5", "7", "8", "12"], correctIndex: 1 },
      { question: "Si la media de 5 datos es 20, y 4 datos son 18, 22, 16, 24, ¿cuál es el 5to?", options: ["18", "20", "22", "24"], correctIndex: 1 },
      { question: "¿Cuál es la desviación estándar de 4, 4, 4, 4?", options: ["0", "1", "2", "4"], correctIndex: 0 },
    ],
    dificil: [
      { question: "Si P(A) = 0.3 y P(B) = 0.5, y son independientes, ¿P(A ∩ B)?", options: ["0.15", "0.30", "0.50", "0.80"], correctIndex: 0 },
      { question: "Datos: 2, 3, 5, 5, 7, 8, 10. ¿Cuál es el rango?", options: ["5", "7", "8", "10"], correctIndex: 2 },
      { question: "La distribución normal tiene μ=50, σ=10. ¿Aprox. qué % está entre 40 y 60?", options: ["50%", "68%", "95%", "99%"], correctIndex: 1 },
      { question: "Si hay 10 personas, ¿cuántas combinaciones de 3 se pueden formar?", options: ["30", "60", "120", "720"], correctIndex: 2 },
      { question: "¿Cuántas permutaciones hay de 5 objetos tomados de 3 en 3?", options: ["10", "15", "60", "120"], correctIndex: 2 },
    ],
  },
  quimica_general: {
    facil: [
      { question: "¿Cuál es el símbolo químico del agua?", options: ["H2O", "CO2", "NaCl", "O2"], correctIndex: 0 },
      { question: "¿Cuántos elementos hay en el agua (H₂O)?", options: ["1", "2", "3", "4"], correctIndex: 1 },
      { question: "¿En qué estado se encuentra el mercurio a temperatura ambiente?", options: ["Sólido", "Líquido", "Gaseoso", "Plasma"], correctIndex: 1 },
      { question: "¿Cuál es el elemento químico con número atómico 1?", options: ["Helio", "Oxígeno", "Hidrógeno", "Carbono"], correctIndex: 2 },
      { question: "¿Qué tipo de enlace se forma entre un metal y un no metal?", options: ["Covalente", "Metálico", "Iónico", "Polar"], correctIndex: 2 },
    ],
    medio: [
      { question: "¿Cuántos electrones tiene el ion Fe³⁺ si el hierro tiene número atómico 26?", options: ["23", "26", "29", "3"], correctIndex: 0 },
      { question: "¿Cuál es la fórmula del cloruro de calcio?", options: ["CaCl", "CaCl₂", "Ca₂Cl", "CaCl₃"], correctIndex: 1 },
      { question: "Balancea: _Fe + _O₂ → _Fe₂O₃. ¿Cuánto es el coeficiente del Fe?", options: ["2", "3", "4", "6"], correctIndex: 2 },
      { question: "¿Cuántos moles de agua se forman al reaccionar 2 moles de H₂ con O₂?", options: ["1", "2", "3", "4"], correctIndex: 1 },
      { question: "¿Cuál es la masa molar del CO₂? (C=12, O=16)", options: ["28 g/mol", "44 g/mol", "32 g/mol", "56 g/mol"], correctIndex: 1 },
    ],
    dificil: [
      { question: "¿Cuál es el número de oxidación del oxígeno en la mayoría de los compuestos?", options: ["+2", "-1", "-2", "+1"], correctIndex: 2 },
      { question: "En una pila de galvanización, ¿qué metal se oxida?", options: ["El más noble", "El menos noble", "Ambos por igual", "Ninguno"], correctIndex: 1 },
      { question: "¿Qué tipo de reacción es: CH₄ + 2O₂ → CO₂ + 2H₂O?", options: ["Descomposición", "Síntesis", "Combustión", "Sustitución"], correctIndex: 2 },
      { question: "¿Cuál es la masa molar del NaOH? (Na=23, O=16, H=1)", options: ["30 g/mol", "40 g/mol", "56 g/mol", "23 g/mol"], correctIndex: 1 },
      { question: "¿Cuántos electrones de valencia tiene el nitrógeno (N)?", options: ["2", "3", "4", "5"], correctIndex: 3 },
    ],
  },
  civilizaciones_preincaicas: {
    facil: [
      { question: "¿En qué zona del Perú se desarrolló la civilización Chavín?", options: ["Costa norte", "Sierra centro", "Selva amazónica", "Altiplano sur"], correctIndex: 1 },
      { question: "¿Qué civilización creó las famosas líneas y geoglifos en el desierto?", options: ["Chavín", "Moche", "Nazca", "Chimú"], correctIndex: 2 },
      { question: "¿Qué civilización preincaica se destacó por su cerámica realista y sus pirámides de adobe?", options: ["Nazca", "Moche", "Chavín", "Wari"], correctIndex: 1 },
      { question: "¿En qué periodo aproximado se desarrolló la civilización Chavín?", options: ["200 a.C. - 600 d.C.", "1200 - 400 a.C.", "100 - 700 d.C.", "1400 - 1532 d.C."], correctIndex: 1 },
      { question: "¿Cuál fue la capital del Reino Chimú antes de ser conquistado por los incas?", options: ["Nazca", "Chan Chan", "Cajamarca", "Tiahuanaco"], correctIndex: 1 },
    ],
    medio: [
      { question: "¿Qué avance agrícola permitió a los moche cultivar en zonas desérticas?", options: ["Terrazas de cultivo", "Canales de irrigación", "Agricultura en camellones", "Semillas modificadas"], correctIndex: 1 },
      { question: "¿Qué material trabajaron especialmente los chimús en su metalurgia?", options: ["Oro y bronce", "Hierro y acero", "Plata y estaño", "Cobre y obsidiana"], correctIndex: 0 },
      { question: "¿Qué civilización preincaica desarrolló los textiles más finos de la antigüedad peruana?", options: ["Chavín", "Nazca", "Paracas", "Moche"], correctIndex: 2 },
      { question: "¿Qué función cumplía el Lanzón monolítico en el templo de Chavín?", options: ["Era una herramienta agrícola", "Representación de una deidad feroz", "Marcador astronómico", "Tumba de un gobernante"], correctIndex: 1 },
      { question: "¿Qué técnica arquitectónica usaron los chimús para construir Chan Chan?", options: ["Piedra tallada con mortero", "Adobe y muros de tapial", "Bloques de granito perfectamente ajustados", "Bambú y materiales orgánicos"], correctIndex: 1 },
    ],
    dificil: [
      { question: "¿Qué criterio cronológico separa a las civilizaciones 'líticas' de las 'horizontes' en la historia antigua del Perú?", options: ["El uso del metal vs. la piedra", "La presencia o ausencia de un gobierno centralizado", "El tamaño de sus ciudades", "La ubicación geográfica"], correctIndex: 1 },
      { question: "¿Qué evidencia arqueológica sugiere que Chavín fue un centro ceremonial de peregrinación regional?", options: ["Los textiles encontrados en la costa", "La variedad de estilos cerámicos de diferentes regiones", "La ausencia de restos óseos", "Los grabados en las piedras"], correctIndex: 1 },
      { question: "¿Qué relación cultural conecta a los nazca con los paracas según los arqueólogos?", options: ["Ambas civilizaciones surgieron simultáneamente", "Los nazca evolucionaron de la cultura Paracas", "Fueron rivales permanentes", "No tienen relación alguna"], correctIndex: 1 },
      { question: "¿Qué avance tecnológico de los chimús evidencian los canales de Moche en la costa norte?", options: ["Uso de maquinaria hidráulica", "Ingeniería hidráulica para irrigar más de 100 km", "Desarrollo de la rueda", "Uso de energía eólica"], correctIndex: 1 },
      { question: "¿Qué debate existe sobre las Líneas de Nazca según investigaciones recientes?", options: ["Si fueron hechas por alienígenas", "Si servían como caminos rituales conectando fuentes de agua", "Si representan constelaciones exactas", "Si fueron creadas en una sola generación"], correctIndex: 1 },
    ],
  },
  imperio_incaico: {
    facil: [
      { question: "¿Cómo se llamaba la capital del Imperio Inca?", options: ["Lima", "Cusco", "Quito", "Bogotá"], correctIndex: 1 },
      { question: "¿Cómo se llamaba el emperador o gobernante supremo del Tahuantinsuyo?", options: ["Curaca", "Sapa Inca", "Quipucamayoc", "Hatun Runa"], correctIndex: 1 },
      { question: "¿Qué sistema de trabajo colectivo obligatorio usaban los incas?", options: ["Encomienda", "Mita", "Tributo", "Feudalismo"], correctIndex: 1 },
      { question: "¿Cómo se llamaba el sistema de registro numérico inca con cuerdas y nudos?", options: ["Jeroglíficos", "Quipus", "Runas", "Tocapu"], correctIndex: 1 },
      { question: "¿En qué año se proclamó la independencia del Perú?", options: ["1810", "1821", "1824", "1826"], correctIndex: 1 },
    ],
    medio: [
      { question: "¿En qué consistía el sistema de mit'a inca?", options: ["Un impuesto pagado en oro", "Trabajo rotativo obligatorio para el Estado", "Un sistema de trueque entre comunidades", "Una forma de comercio entre curacas"], correctIndex: 1 },
      { question: "¿Cuántas regiones conformaban el Tahuantinsuyo?", options: ["Dos", "Tres", "Cuatro", "Seis"], correctIndex: 2 },
      { question: "¿Qué función tenían los quipus en el gobierno inca?", options: ["Decorar los templos", "Registrar información numérica y administrativa", "Comunicarse con los dioses", "Marcar territorios"], correctIndex: 1 },
      { question: "¿Qué red vial conectaba todo el Imperio Inca y medía más de 30,000 km?", options: ["La Vía Apia", "El Qhapaq Ñan", "El Camino Real", "La Ruta de la Seda"], correctIndex: 1 },
      { question: "¿Cuál era la función de los tambos en la red de caminos inca?", options: ["Templos religiosos", "Puestos militares", "Estaciones de descanso y almacenamiento", "Mercados de trueque"], correctIndex: 2 },
    ],
    dificil: [
      { question: "¿Qué estrategia usó Pachacútec para controlar los territorios conquistados?", options: ["Dejarlos completamente autónomos", "Reasentar poblaciones leales y reemplazar curacas", "Destruir todas sus ciudades", "No dejó ningún tipo de gobierno local"], correctIndex: 1 },
      { question: "¿Qué complejidad administrativa tenía el imperio bajo Túpac Yupanqui?", options: ["Gobernaba solo con ayuda de sus hermanos", "Mantenía un ejército permanente y realizaba expediciones hasta Quito", "No necesitaba administración porque no había impuestos", "Delegaba todo el gobierno a los españoles"], correctIndex: 1 },
      { question: "¿Qué relación existía entre la mit'a inca y la mit'a colonial?", options: ["No tienen relación alguna", "La colonial copió el sistema de trabajo rotativo pero lo hizo más explotador", "La colonial eliminó completamente la mit'a", "Ambas eran voluntarias"], correctIndex: 1 },
      { question: "¿Qué evidencia arqueológica demuestra la capacidad de planificación urbana inca?", options: ["Los quipus encontrados en las tumbas", "La precisión de Sacsayhuamán con bloques de más de 100 toneladas", "Los textiles encontrados en Machu Picchu", "Los restos de animales domesticados"], correctIndex: 1 },
      { question: "¿Cuál fue la causa inmediata de la guerra civil entre Atahualpa y Huáscar?", options: ["La llegada de los españoles", "La muerte de Huayna Cápac y la disputa por la sucesión", "Una rebelión de los curacas", "La escasez de alimentos en el imperio"], correctIndex: 1 },
    ],
  },
  conquista_colonia: {
    facil: [
      { question: "¿Quién lideró la conquista española del Perú?", options: ["Hernán Cortés", "Francisco Pizarro", "Pedro de Valdivia", "Diego de Almagro"], correctIndex: 1 },
      { question: "¿En qué año capturaron los españoles al emperador Atahualpa?", options: ["1521", "1532", "1540", "1550"], correctIndex: 1 },
      { question: "¿En qué ciudad fue capturado Atahualpa?", options: ["Cusco", "Lima", "Cajamarca", "Quito"], correctIndex: 2 },
      { question: "¿Qué ciudad fundó Francisco Pizarro como capital del Perú?", options: ["Cusco", "Arequipa", "Trujillo", "Lima"], correctIndex: 3 },
      { question: "¿Qué sistema de gobierno estableció España en el Perú?", options: ["República", "Virreinato", "Monarquía constitucional", "Democracia"], correctIndex: 1 },
    ],
    medio: [
      { question: "¿En qué consistía el sistema de castas en la colonia?", options: ["Igualdad racial para todos los habitantes", "Separación de la sociedad por origen racial y jerarquía", "Solo españoles vivían en las ciudades", "Todos los mestizos eran nobles"], correctIndex: 1 },
      { question: "¿Qué era la encomienda en el sistema colonial?", options: ["Un tipo de escuela para indígenas", "Un sistema que otorgaba indígenas a españoles para explotar su trabajo", "Una forma de gobierno local", "Un impuesto que pagaban los españoles"], correctIndex: 1 },
      { question: "¿Qué diferencia existía entre criollos y peninsulares?", options: ["No había diferencia", "Los criollos nacían en América, los peninsulares en España", "Los peninsulares eran más pobres", "Los criollos controlaban el comercio"], correctIndex: 1 },
      { question: "¿Qué función cumplía el cabildo en las ciudades coloniales?", options: ["Gobierno religioso local", "Administración municipal y justicia local", "Comercio internacional", "Defensa militar"], correctIndex: 1 },
      { question: "¿Qué rama de la Iglesia tuvo gran influencia en la colonia peruana?", options: ["Iglesia protestante", "Compañía de Jesús y otros órdenes religiosos", "Iglesia ortodoxa", "Iglesia copta"], correctIndex: 1 },
    ],
    dificil: [
      { question: "¿Qué motivó la rebelión de Túpac Amaru II en 1780?", options: ["El deseo de ser rey del Perú", "Los abusos de la mita colonial y el sistema de corregidores", "La llegada de los ingleses", "El terremoto de 1746"], correctIndex: 1 },
      { question: "¿Qué consecuencias tuvo la rebelión de Túpac Amaru II para la sociedad colonial?", options: ["Abolición de la mita", "Represión feroz y fortalecimiento del control colonial", "Independencia inmediata del Perú", "Creación de un nuevo virreinato"], correctIndex: 1 },
      { question: "¿Qué actividad económica dominó el comercio del Virreinato del Perú en los siglos XVI-XVII?", options: ["Agricultura de exportación", "La exportación de plata de Potosí a través del Galeón de Manila", "El comercio de esclavos desde África", "La pesca del bacalao"], correctIndex: 1 },
      { question: "¿Qué impacto cultural tuvo la colonización española en la sociedad peruana?", options: ["Preservación intacta de todas las tradiciones incas", "Mezcla cultural mestiza con imposición del español y catolicismo", "Aislamiento total de las culturas indígenas", "Desaparición completa de las lenguas nativas"], correctIndex: 1 },
      { question: "¿Qué eventos internacionales influyeron en el creciente descontento colonial hacia el siglo XVIII?", options: ["La Revolución Francesa y la independencia de EE.UU.", "La caída del Imperio Romano", "La invención de la imprenta", "El descubrimiento de América"], correctIndex: 0 },
    ],
  },
  guerra_del_pacifico: {
    facil: [
      { question: "¿Qué países lucharon en la Guerra del Pacífico contra Perú?", options: ["Argentina y Colombia", "Chile y Ecuador", "Chile y Bolivia", "Brasil y Chile"], correctIndex: 2 },
      { question: "¿En qué años se libró la Guerra del Pacífico?", options: ["1864-1870", "1879-1884", "1895-1900", "1910-1918"], correctIndex: 1 },
      { question: "¿Qué recurso natural provocó el conflicto por los territorios del norte?", options: ["El petróleo", "El salitre (nitrato)", "El oro", "El cobre"], correctIndex: 1 },
      { question: "¿En qué batalla se selló la derrota definitiva del Perú?", options: ["Batalla de Tarapacá", "Batalla de Angamos", "Batalla de San Francisco", "Batalla de Ayacucho"], correctIndex: 2 },
      { question: "¿Qué tratado puso fin a la Guerra del Pacífico en 1883?", options: ["Tratado de Lima", "Tratado de Ancón", "Tratado de Versalles", "Tratado de Tordesillas"], correctIndex: 1 },
    ],
    medio: [
      { question: "¿Qué territorios perdió Perú con el Tratado de Ancón?", options: ["Loreto y San Martín", "Arica y Tacna (posteriormente devuelta)", "Cusco y Puno", "Ica y Arequipa"], correctIndex: 1 },
      { question: "¿Qué hizo Bolivia tras la Guerra del Pacífico en cuanto a su acceso al mar?", options: ["Recuperó su costa en 1900", "Perdió definitivamente su franja costera", "Amplió su costa hacia el norte", "No se vio afectada"], correctIndex: 1 },
      { question: "¿Qué batalla naval fue decisiva en la Guerra del Pacífico y terminó con la escuadra peruana?", options: ["Batalla de Iquique", "Batalla de Angamos", "Batalla de Pacocha", "Batalla de Callao"], correctIndex: 1 },
      { question: "¿Qué función cumplía el Tratado de Ancón respecto a la provincia de Tacna?", options: ["La entregaba inmediatamente a Chile", "La ponía bajo administración chilena por 10 años", "La declaraba territorio neutral", "La entregaba a Bolivia"], correctIndex: 1 },
      { question: "¿Qué hazaña militar realizó el monitor Huáscar bajo Miguel Grau antes de su captura?", options: ["Invadió territorio chileno por tierra", "Mantuvo la resistencia naval peruana durante más de un año", "Capturó buques británicos", "Destruyó el puerto de Valparaíso"], correctIndex: 1 },
    ],
    dificil: [
      { question: "¿Qué factor económico específico convirtió al salitre en causa de guerra?", options: ["Era el único recurso del norte", "Chile explotaba ilícitamente los yacimientos en territorio disputado", "Bolivia tenía el monopolio mundial del salitre", "El salitre era necesario para fabricar armas nucleares"], correctIndex: 1 },
      { question: "¿Qué impacto económico a largo plazo tuvo la pérdida del salitre para el Perú?", options: ["El Perú se industrializó rápidamente", "Perdió una fuente de riqueza fiscal y sufrió deuda externa prolongada", "No hubo consecuencias económicas", "El Perú se convirtió en potencia minera"], correctIndex: 1 },
      { question: "¿Qué disputa diplomática entre Perú y Chile sobre Tacna y Arica se resolvió en 1929?", options: ["El Protocolo de Rancón", "El Tratado de Lima de 1929", "La Conferencia de Washington", "El Tratado de Ancón"], correctIndex: 1 },
      { question: "¿Qué consecuencias políticas internas tuvo la derrota en la Guerra del Pacífico para el Perú?", options: ["Fortalecimiento de la democracia", "Inestabilidad política y cambios frecuentes de gobierno", "No hubo cambios políticos", "Se estableció una monarquía"], correctIndex: 1 },
      { question: "¿Qué reclamo territorial mantiene Bolivia respecto a la Guerra del Pacífico hasta la actualidad?", options: ["Reclama la región de Loreto", "Reclama acceso soberano al mar por territorio chileno", "Reclama la devolución de Tacna", "No tiene reclamos activos"], correctIndex: 1 },
    ],
  },
  historia_peru: {
    facil: [
      { question: "¿Quién fue el primer emperador del Tahuantinsuyo?", options: ["Túpac Inca Yupanqui", "Pachacútec", "Huayna Cápac", "Atahualpa"], correctIndex: 1 },
      { question: "¿En qué año llegó Francisco Pizarro al Perú?", options: ["1492", "1532", "1545", "1600"], correctIndex: 1 },
      { question: "¿Qué civilización preincaica construyó las líneas de Nazca?", options: ["Chavín", "Paracas", "Nazca", "Moche"], correctIndex: 2 },
      { question: "¿En qué año se proclamó la independencia del Perú?", options: ["1810", "1821", "1824", "1826"], correctIndex: 1 },
      { question: "¿Qué río atraviesa la ciudad de Lima, capital del Perú?", options: ["Río Amazonas", "Río Urubamba", "Río Rímac", "Río Mantaro"], correctIndex: 2 },
    ],
    medio: [
      { question: "¿Qué sistema económico organizaba el Imperio Inca?", options: ["Mercado libre", "Tributario en metales", "Redistribución comunal (mit'a)", "Comercio de trueque"], correctIndex: 2 },
      { question: "¿Quién fue el último emperador inca?", options: ["Pachacútec", "Túpac Amaru", "Atahualpa", "Huáscar"], correctIndex: 1 },
      { question: "¿En qué batalla se selló la independencia del Perú?", options: ["Batalla de Ayacucho", "Batalla de Junín", "Batalla de Pichincha", "Batalla de Chacabuco"], correctIndex: 0 },
      { question: "¿Qué periodo de la historia peruana se conoce como la Élite del Guano?", options: ["1821-1840", "1840-1860", "1860-1880", "1880-1900"], correctIndex: 1 },
      { question: "¿Qué civilización preincaica desarrolló el sistema de quipus para registrar información?", options: ["Moche", "Nazca", "Wari", "Incas"], correctIndex: 2 },
    ],
    dificil: [
      { question: "¿En qué año se produjo la rebelión de Túpac Amaru II?", options: ["1742", "1780", "1814", "1820"], correctIndex: 1 },
      { question: "¿Qué tratado puso fin a la Guerra del Pacífico entre Perú, Bolivia y Chile?", options: ["Tratado de Ancón", "Tratado de Lima", "Tratado de Rancón", "Tratado de Ancon"], correctIndex: 0 },
      { question: "¿En qué año se firmó el Tratado de Tordesillas, que dividió el mundo entre España y Portugal?", options: ["1492", "1494", "1500", "1512"], correctIndex: 1 },
      { question: "¿Qué virrey del Perú organizó la expedición que conquistó Chile?", options: ["Virrey Toledo", "Virrey Andrés Hurtado de Mendoza", "Virrey La Serna", "Virrey Abascal"], correctIndex: 1 },
      { question: "¿En qué año se produjo la captura del emperador Atahualpa en Cajamarca?", options: ["1528", "1530", "1532", "1533"], correctIndex: 2 },
    ],
  },
  historia_universal: {
    facil: [
      { question: "¿En qué año comenzó la Primera Guerra Mundial?", options: ["1912", "1914", "1916", "1918"], correctIndex: 1 },
      { question: "¿Qué civilización construyó las pirámides de Giza?", options: ["Romana", "Griega", "Egipcia", "Persa"], correctIndex: 2 },
      { question: "¿Quién fue el líder de la Revolución Francesa más conocido por el Reinado del Terror?", options: ["Napoleón Bonaparte", "Maximilien Robespierre", "Louis XVI", "Georges Danton"], correctIndex: 1 },
      { question: "¿En qué año cayó el Muro de Berlín?", options: ["1987", "1989", "1991", "1993"], correctIndex: 1 },
      { question: "¿Qué Imperio construyó la Gran Muralla China?", options: ["Imperio Mongol", "Imperio Otomano", "Imperio Chino", "Imperio Romano"], correctIndex: 2 },
    ],
    medio: [
      { question: "¿Qué tratado puso fin a la Primera Guerra Mundial?", options: ["Tratado de Versalles", "Tratado de París", "Tratado de Viena", "Tratado de Tordesillas"], correctIndex: 0 },
      { question: "¿En qué año se produjo la Revolución Rusa?", options: ["1905", "1910", "1917", "1922"], correctIndex: 2 },
      { question: "¿Qué movimiento social lideró Mahatma Gandhi en la India?", options: ["Independencia por armas", "Resistencia pacífica", "Revolución armada", "Separatismo"], correctIndex: 1 },
      { question: "¿Qué conflicto se denominó la Guerra Fría?", options: ["EE.UU. vs. URSS (tensión política e ideológica)", "EE.UU. vs. China", "Europa vs. Asia", "Inglaterra vs. Francia"], correctIndex: 0 },
      { question: "¿En qué año comenzó la Segunda Guerra Mundial?", options: ["1937", "1939", "1941", "1945"], correctIndex: 1 },
    ],
    dificil: [
      { question: "¿En qué año se firmó la Paz de Westfalia, que sentó las bases del sistema de estados modernos?", options: ["1588", "1618", "1648", "1713"], correctIndex: 2 },
      { question: "¿Qué evento marcó el inicio oficial de la Revolución Francesa?", options: ["Asalto a la Bastilla", "Declaración de los Derechos del Hombre", "Ejecución de Luis XVI", "Conjura de los Igualitarios"], correctIndex: 0 },
      { question: "¿En qué año se produjo la Batalla de Waterloo, que puso fin al imperio de Napoleón?", options: ["1804", "1812", "1815", "1821"], correctIndex: 2 },
      { question: "¿Qué sistema económico fue propuesto por Karl Marx en 'El Capital'?", options: ["Liberalismo", "Capitalismo de libre mercado", "Socialismo/Comunismo", "Mercantilismo"], correctIndex: 2 },
      { question: "¿En qué año se firmó el Tratado de Tordesillas entre España y Portugal?", options: ["1492", "1494", "1498", "1500"], correctIndex: 1 },
    ],
  },
  revolucion_industrial: {
    facil: [
      { question: "¿En qué siglo comenzó la Revolución Industrial?", options: ["Siglo XVII", "Siglo XVIII", "Siglo XIX", "Siglo XX"], correctIndex: 1 },
      { question: "¿Qué invento fue clave para el inicio de la Revolución Industrial?", options: ["La brújula", "La máquina de vapor", "El teléfono", "La imprenta"], correctIndex: 1 },
      { question: "¿En qué país comenzó la Revolución Industrial?", options: ["Francia", "Alemania", "Gran Bretaña", "Estados Unidos"], correctIndex: 2 },
      { question: "¿Qué combustible se usaba principalmente en las primeras máquinas de vapor?", options: ["Petróleo", "Carbón", "Gas natural", "Madera"], correctIndex: 1 },
      { question: "¿Cómo se llamaban los grandes establecimientos donde se concentraba la producción industrial?", options: ["Talleres", "Fábricas", "Gremios", "Mercados"], correctIndex: 1 },
    ],
    medio: [
      { question: "¿Qué fenómeno social provocó la migración masiva del campo a la ciudad durante la Revolución Industrial?", options: ["La peste negra", "La urbanización", "Las guerras napoleónicas", "El descubrimiento de América"], correctIndex: 1 },
      { question: "¿Cómo se llamaba el movimiento de trabajadores que exigía mejoras laborales y destruía máquinas?", options: ["Sindicalismo", "Cartismo", "Ludismo", "Socialismo utópico"], correctIndex: 2 },
      { question: "¿Qué clase social surgió como dueña de los medios de producción durante la Revolución Industrial?", options: ["El proletariado", "La nobleza", "La burguesía industrial", "El campesinado"], correctIndex: 2 },
      { question: "¿Qué ley británica de 1833 reguló el trabajo infantil en las fábricas?", options: ["Ley de Fábricas", "Ley de Pobres", "Ley de Gremios", "Ley de Salarios"], correctIndex: 0 },
      { question: "¿Qué medio de transporte revolucionó el comercio y la comunicación durante la Revolución Industrial?", options: ["El automóvil", "El ferrocarril", "El avión", "El barco de vela"], correctIndex: 1 },
    ],
    dificil: [
      { question: "¿Qué economista escribió 'La riqueza de las naciones' y defendió el libre mercado durante la Revolución Industrial?", options: ["Karl Marx", "Adam Smith", "David Ricardo", "John Stuart Mill"], correctIndex: 1 },
      { question: "¿Qué sistema económico propuso Robert Owen como alternativa al capitalismo industrial?", options: ["Comunismo", "Socialismo utópico", "Anarquismo", "Fascismo"], correctIndex: 1 },
      { question: "¿Qué innovación tecnológica de Henry Bessemer revolucionó la producción de acero en el siglo XIX?", options: ["El alto horno", "El convertidor Bessemer", "La forja hidráulica", "El laminador"], correctIndex: 1 },
      { question: "¿Qué fue el 'Great Game' y cómo se relacionó con la Revolución Industrial?", options: ["Un deporte inglés", "La rivalidad colonial entre UK y Rusia por Asia", "Una feria industrial mundial", "Un movimiento sindical"], correctIndex: 1 },
      { question: "¿Qué consecuencia demográfica tuvo la Revolución Industrial en Europa?", options: ["Disminución de la población", "Explosión demográfica y mayor esperanza de vida", "Migración masiva a Asia", "Estancamiento poblacional"], correctIndex: 1 },
    ],
  },
  guerra_mundial_1: {
    facil: [
      { question: "¿En qué año comenzó la Primera Guerra Mundial?", options: ["1912", "1914", "1916", "1918"], correctIndex: 1 },
      { question: "¿Qué evento fue el detonante inmediato de la Primera Guerra Mundial?", options: ["La invasión de Bélgica", "El asesinato del archiduque Francisco Fernando", "El hundimiento del Lusitania", "La declaración de guerra de Alemania"], correctIndex: 1 },
      { question: "¿Qué países formaban la Triple Entente?", options: ["Alemania, Austria-Hungría, Italia", "Francia, Reino Unido, Rusia", "EE.UU., Reino Unido, Francia", "Rusia, Alemania, Francia"], correctIndex: 1 },
      { question: "¿Qué países formaban la Triple Alianza?", options: ["Francia, Reino Unido, Rusia", "Alemania, Austria-Hungría, Italia", "EE.UU., Japón, Reino Unido", "Rusia, Alemania, Italia"], correctIndex: 1 },
      { question: "¿En qué año terminó la Primera Guerra Mundial?", options: ["1917", "1918", "1919", "1920"], correctIndex: 1 },
    ],
    medio: [
      { question: "¿Cómo se llamó el sistema de combate caracterizado por zanjas excavadas en el frente occidental?", options: ["Guerra relámpago", "Guerra de trincheras", "Guerra de guerrillas", "Guerra naval"], correctIndex: 1 },
      { question: "¿Qué batalla de 1916 se considera la más larga y sangrienta de la Primera Guerra Mundial?", options: ["Batalla de Somme", "Batalla de Verdún", "Batalla de Ypres", "Batalla de Marne"], correctIndex: 1 },
      { question: "¿Qué tratado de paz impuso duras condiciones a Alemania al final de la Primera Guerra Mundial?", options: ["Tratado de París", "Tratado de Versalles", "Tratado de Viena", "Tratado de Tordesillas"], correctIndex: 1 },
      { question: "¿Qué nueva arma química se utilizó por primera vez en la Primera Guerra Mundial?", options: ["Napalm", "Gas mostaza", "Agente naranja", "Fósforo blanco"], correctIndex: 1 },
      { question: "¿Qué país abandonó la guerra en 1917 tras la Revolución Rusa?", options: ["Francia", "Rusia", "Italia", "Austria-Hungría"], correctIndex: 1 },
    ],
    dificil: [
      { question: "¿Qué cláusula del Tratado de Versalles obligó a Alemania a aceptar toda la responsabilidad de la guerra?", options: ["Cláusula de reparaciones", "Cláusula de culpabilidad", "Cláusula de desarme", "Cláusula territorial"], correctIndex: 1 },
      { question: "¿Qué imperio desapareció tras la Primera Guerra Mundial dividiéndose en varios países de Europa Central?", options: ["Imperio Otomano", "Imperio Austrohúngaro", "Imperio Ruso", "Imperio Alemán"], correctIndex: 1 },
      { question: "¿Cuál fue una consecuencia económica directa de las reparaciones de guerra impuestas a Alemania?", options: ["El milagro alemán", "La hiperinflación de 1923", "La unificación alemana", "El Plan Dawes"], correctIndex: 1 },
      { question: "¿Qué país no fue invitado a la Conferencia de Paz de París de 1919?", options: ["Alemania", "Francia", "Reino Unido", "Estados Unidos"], correctIndex: 0 },
      { question: "¿Cómo contribuyó el Tratado de Versalles al surgimiento de la Segunda Guerra Mundial?", options: ["Garantizó la paz", "Generó resentimiento y crisis económica en Alemania", "Desarmó a todos los países", "Creó la Liga de Naciones"], correctIndex: 1 },
    ],
  },
  guerra_mundial_2: {
    facil: [
      { question: "¿En qué año comenzó la Segunda Guerra Mundial?", options: ["1937", "1939", "1941", "1945"], correctIndex: 1 },
      { question: "¿Quién fue el líder de la Alemania nazi?", options: ["Mussolini", "Hitler", "Stalin", "Churchill"], correctIndex: 1 },
      { question: "¿Qué país invadió Alemania para iniciar la Segunda Guerra Mundial?", options: ["Francia", "Polonia", "Checoslovaquia", "Unión Soviética"], correctIndex: 1 },
      { question: "¿Qué países formaban el Eje?", options: ["EE.UU., Reino Unido, URSS", "Alemania, Italia, Japón", "Francia, Reino Unido, Polonia", "China, URSS, EE.UU."], correctIndex: 1 },
      { question: "¿En qué año terminó la Segunda Guerra Mundial?", options: ["1944", "1945", "1946", "1947"], correctIndex: 1 },
    ],
    medio: [
      { question: "¿Cómo se llamó el genocidio sistemático de seis millones de judíos por parte de la Alemania nazi?", options: ["La Solución Final", "El Holocausto", "La purificación racial", "La limpieza étnica"], correctIndex: 1 },
      { question: "¿Qué evento llevó a Estados Unidos a entrar en la Segunda Guerra Mundial?", options: ["La invasión de Polonia", "El ataque a Pearl Harbor", "La batalla de Inglaterra", "La caída de Francia"], correctIndex: 1 },
      { question: "¿Qué ciudades japonesas fueron destruidas por bombas atómicas en 1945?", options: ["Tokio y Osaka", "Hiroshima y Nagasaki", "Kioto y Yokohama", "Kobe y Sapporo"], correctIndex: 1 },
      { question: "¿Cómo se llamó la invasión aliada de Normandía en 1944?", options: ["Operación Barbarroja", "Operación Overlord", "Operación Torch", "Operación Market Garden"], correctIndex: 1 },
      { question: "¿Qué teatro de guerra incluyó las batallas de Midway, Iwo Jima y Okinawa?", options: ["Teatro europeo", "Teatro del Pacífico", "Teatro africano", "Teatro del Atlántico"], correctIndex: 1 },
    ],
    dificil: [
      { question: "¿Qué nombre recibieron los juicios internacionales contra los líderes nazis tras la Segunda Guerra Mundial?", options: ["Juicios de La Haya", "Juicios de Núremberg", "Juicios de Tokio", "Juicios de Ginebra"], correctIndex: 1 },
      { question: "¿Qué fue la 'Operación Barbarroja'?", options: ["La invasión de Polonia", "La invasión alemana de la Unión Soviética", "La invasión de Francia", "El desembarco en Normandía"], correctIndex: 1 },
      { question: "¿Qué conferencia de 1945 dividió Alemania en zonas de ocupación?", options: ["Conferencia de Yalta", "Conferencia de Potsdam", "Conferencia de Teherán", "Conferencia de Ginebra"], correctIndex: 1 },
      { question: "¿Qué organización internacional se creó en 1945 para mantener la paz mundial tras la guerra?", options: ["La Liga de Naciones", "Las Naciones Unidas", "La OTAN", "El Pacto de Varsovia"], correctIndex: 1 },
      { question: "¿Cómo se llamó el plan estadounidense de ayuda económica para reconstruir Europa tras la Segunda Guerra Mundial?", options: ["Plan Marshall", "Plan Truman", "Plan Roosevelt", "Plan Eisenhower"], correctIndex: 0 },
    ],
  },
  guerra_franco_prusiana: {
    facil: [
      { question: "¿En qué año ocurrió la Guerra Franco-Prusiana?", options: ["1866-1867", "1870-1871", "1880-1881", "1890-1891"], correctIndex: 1 },
      { question: "¿Quién era el canciller de Prusia que impulsó la guerra contra Francia?", options: ["Kaiser Guillermo I", "Otto von Bismarck", "Helmuth von Moltke", "Paul von Hindenburg"], correctIndex: 1 },
      { question: "¿Quién era el emperador de Francia durante la guerra?", options: ["Luis Felipe", "Napoleón III", "Napoleón Bonaparte", "Carlos X"], correctIndex: 1 },
      { question: "¿Qué país del sur de Alemania se unió al conflicto del lado prusiano?", options: ["Austria", "Baviera", "Suiza", "Dinamarca"], correctIndex: 1 },
      { question: "¿Cuál fue el resultado de la guerra?", options: ["Victoria francesa", "Victoria prusiana", "Empate", "Victoria británica"], correctIndex: 1 },
    ],
    medio: [
      { question: "¿En qué batalla decisiva fue capturado Napoleón III?", options: ["Batalla de Metz", "Batalla de Sedán", "Batalla de París", "Batalla de Wissembourg"], correctIndex: 1 },
      { question: "¿Qué evento ocurrió en el Palacio de Versalles el 18 de enero de 1871?", options: ["La rendición de Francia", "La proclamación del Imperio Alemán", "La firma del tratado de paz", "La coronación de Napoleón III"], correctIndex: 1 },
      { question: "¿Qué tratado puso fin a la Guerra Franco-Prusiana?", options: ["Tratado de París", "Tratado de Frankfurt", "Tratado de Viena", "Tratado de Versalles"], correctIndex: 1 },
      { question: "¿Qué territorio fue anexado por Alemania como resultado de la guerra?", options: ["Normandía", "Alsacia y Lorena", "Borgoña", "Provenza"], correctIndex: 1 },
      { question: "¿Qué gobierno revolucionario se estableció en París tras la derrota francesa en 1871?", options: ["La Comuna de París", "La Asamblea Nacional", "El Directorio", "El Consulado"], correctIndex: 0 },
    ],
    dificil: [
      { question: "¿Qué estrategia militar prusiana fue clave para derrotar a Francia en la guerra?", options: ["Guerra de trincheras", "Guerra relámpago moderna", "Uso del ferrocarril para movilización rápida", "Guerra naval"], correctIndex: 2 },
      { question: "¿Cómo afectó la Guerra Franco-Prusiana al equilibrio de poder europeo?", options: ["Francia se fortaleció", "Alemania surgió como potencia continental dominante", "Austria se convirtió en la potencia principal", "El Reino Unido dominó Europa"], correctIndex: 1 },
      { question: "¿Qué consecuencia tuvo la derrota francesa en la política interna de Francia?", options: ["La restauración de la monarquía", "El establecimiento de la Tercera República Francesa", "La dictadura de Napoleón III", "La unión con Bélgica"], correctIndex: 1 },
      { question: "¿Qué papel jugó el 'Telegrama de Ems' en el inicio de la guerra?", options: ["Fue un tratado secreto", "Bismarck lo manipuló para provocar a Francia", "Era una declaración de guerra formal", "Fue ignorado por ambos bandos"], correctIndex: 1 },
      { question: "¿Qué nueva potencia europea surgió como resultado directo de la Guerra Franco-Prusiana?", options: ["El Imperio Austrohúngaro", "El Imperio Alemán unificado", "El Reino de Italia", "El Imperio Ruso"], correctIndex: 1 },
    ],
  },
  revolucion_rusa: {
    facil: [
      { question: "¿En qué año ocurrió la Revolución Rusa?", options: ["1905", "1914", "1917", "1922"], correctIndex: 2 },
      { question: "¿Quién era el zar de Rusia derrocado por la revolución?", options: ["Pedro el Grande", "Nicolás II", "Alejandro II", "Iván el Terrible"], correctIndex: 1 },
      { question: "¿Quién lideró el Partido Bolchevique durante la Revolución Rusa?", options: ["Trotsky", "Lenin", "Stalin", "Kerenski"], correctIndex: 1 },
      { question: "¿Qué ideología política siguieron los bolcheviques?", options: ["Capitalismo", "Marxismo-Leninismo", "Fascismo", "Monarquismo"], correctIndex: 1 },
      { question: "¿Qué palacio fue asaltado en octubre de 1917 durante la revolución bolchevique?", options: ["Palacio de Invierno", "Palacio de Verano", "Kremlin", "Palacio de Catalina"], correctIndex: 0 },
    ],
    medio: [
      { question: "¿Qué diferencia hubo entre la Revolución de Febrero y la de Octubre de 1917?", options: ["Febrero fue campesina, Octubre fue urbana", "Febrero derrocó al zar, Octubre llevó a los bolcheviques al poder", "Febrero fue pacífica, Octubre fue violenta", "Febrero ocurrió en Moscú, Octubre en San Petersburgo"], correctIndex: 1 },
      { question: "¿Qué grupo luchó contra los bolcheviques en la guerra civil rusa?", options: ["Los mencheviques", "El Ejército Blanco", "Los kadetes", "Los socialrevolucionarios"], correctIndex: 1 },
      { question: "¿En qué año se fundó la Unión Soviética (URSS)?", options: ["1917", "1922", "1924", "1930"], correctIndex: 1 },
      { question: "¿Qué política económica implementó Lenin durante la guerra civil?", options: ["NEP (Nueva Política Económica)", "Comunismo de guerra", "Colectivización forzosa", "Capitalismo de Estado"], correctIndex: 1 },
      { question: "¿Cómo se llamaba el parlamento ruso que existía antes de la revolución?", options: ["Soviet", "Duma", "Asamblea Constituyente", "Congreso de los Diputados"], correctIndex: 1 },
    ],
    dificil: [
      { question: "¿Cómo aplicó Lenin la teoría marxista a las condiciones de Rusia?", options: ["Esperó a que el capitalismo madurara", "Propugnó una revolución liderada por el partido de vanguardia", "Buscó alianza con la burguesía", "Promovió reformas graduales"], correctIndex: 1 },
      { question: "¿Qué factor fue clave en el ascenso de Stalin al poder tras la muerte de Lenin?", options: ["Su liderazgo militar", "Su control del Partido Comunista y el aparato burocrático", "Su popularidad entre los campesinos", "Su alianza con Trotsky"], correctIndex: 1 },
      { question: "¿Qué consecuencias tuvo la Revolución Rusa en el movimiento comunista global?", options: ["Fue ignorada por otros países", "Inspiró movimientos comunistas y revoluciones en todo el mundo", "Fortaleció el capitalismo", "Creó una alianza con EE.UU."], correctIndex: 1 },
      { question: "¿Qué fue el 'Comunismo de Guerra' y qué efectos tuvo?", options: ["Una alianza militar", "Política de nacionalización y requisición forzosa de alimentos", "Un tratado de paz con Alemania", "Un plan de industrialización"], correctIndex: 1 },
      { question: "¿Qué fue el 'Testamento de Lenin' y qué advertía?", options: ["Un plan económico", "Una carta criticando a Stalin y advirtiendo sobre su concentración de poder", "Una declaración de guerra", "Un tratado de comercio"], correctIndex: 1 },
    ],
  },
  guerra_fria: {
    facil: [
      { question: "¿Entre qué dos superpotencias se desarrolló la Guerra Fría?", options: ["Reino Unido y Francia", "EE.UU. y URSS", "China y Japón", "Alemania y Rusia"], correctIndex: 1 },
      { question: "¿En qué año se considera que comenzó la Guerra Fría?", options: ["1945", "1947", "1950", "1953"], correctIndex: 1 },
      { question: "¿En qué año cayó el Muro de Berlín?", options: ["1987", "1989", "1991", "1993"], correctIndex: 1 },
      { question: "¿Qué organización militar liderada por EE.UU. se creó en 1949?", options: ["Pacto de Varsovia", "OTAN", "Liga de Naciones", "ONU"], correctIndex: 1 },
      { question: "¿Qué bloque era comunista durante la Guerra Fría?", options: ["El bloque occidental", "El bloque del Este", "El bloque neutral", "El bloque asiático"], correctIndex: 1 },
    ],
    medio: [
      { question: "¿Qué fue la Crisis de los Misiles en Cuba de 1962?", options: ["Un terremoto en Cuba", "Un enfrentamiento entre EE.UU. y URSS por misiles soviéticos en Cuba", "Una invasión de Cuba a EE.UU.", "Una prueba nuclear cubana"], correctIndex: 1 },
      { question: "¿Qué guerra de la Guerra Fría se conoce como 'guerra proxy' entre EE.UU. y URSS?", options: ["Guerra de las Malvinas", "Guerra de Vietnam", "Guerra de Corea", "Guerra de los Seis Días"], correctIndex: 1 },
      { question: "¿Qué carrera tecnológica caracterizó la Guerra Fría?", options: ["Carrera naval", "Carrera espacial", "Carrera aérea", "Carrera ferroviaria"], correctIndex: 1 },
      { question: "¿Qué país fue el primero en enviar un ser humano al espacio?", options: ["EE.UU.", "URSS", "China", "Alemania"], correctIndex: 1 },
      { question: "¿Qué separaba físicamente a Berlín Oriental de Berlín Occidental?", options: ["Un río", "El Muro de Berlín", "Una zanja", "Un campo minado"], correctIndex: 1 },
    ],
    dificil: [
      { question: "¿Qué fue la política de 'détente' durante la Guerra Fría?", options: ["Una escalada militar", "Un periodo de relajación de tensiones entre EE.UU. y URSS", "Una alianza económica", "Una doctrina de guerra nuclear"], correctIndex: 1 },
      { question: "¿Qué fue la Doctrina Truman?", options: ["Un plan económico", "La política de contención del comunismo", "Una alianza militar", "Un programa espacial"], correctIndex: 1 },
      { question: "¿Qué fue la Perestroika de Gorbachov?", options: ["Un plan militar", "Una reestructuración económica y política de la URSS", "Una alianza con EE.UU.", "Una doctrina de guerra"], correctIndex: 1 },
      { question: "¿Qué fue la Glasnost impulsada por Gorbachov?", options: ["Reforma económica", "Política de apertura y transparencia informativa", "Un tratado de desarme", "Una invasión militar"], correctIndex: 1 },
      { question: "¿Qué evento de 1991 marcó el fin definitivo de la Guerra Fría?", options: ["La caída del Muro de Berlín", "La disolución de la Unión Soviética", "La reunificación alemana", "El fin de la guerra de Afganistán"], correctIndex: 1 },
    ],
  },
  geografia_general: {
    facil: [
      { question: "¿Cuántos continentes hay en el mundo?", options: ["5", "6", "7", "8"], correctIndex: 2 },
      { question: "¿Cuál es el océano más grande del mundo?", options: ["Atlántico", "Índico", "Pacífico", "Ártico"], correctIndex: 2 },
      { question: "¿Cuántas regiones tiene el Perú?", options: ["24", "25", "32", "35"], correctIndex: 2 },
      { question: "¿Cuáles son las tres franjas naturales del Perú?", options: ["Norte, Centro, Sur", "Costa, Sierra, Amazonía", "Altiplano, Selva, Costa", "Montaña, Valle, Costa"], correctIndex: 1 },
      { question: "¿En qué continente se encuentra el Perú?", options: ["Asia", "Europa", "África", "América"], correctIndex: 3 },
    ],
    medio: [
      { question: "¿Cuál es la región más poblada del Perú?", options: ["Arequipa", "Lima", "La Libertad", "Cusco"], correctIndex: 1 },
      { question: "¿Qué río es el más largo que atraviesa la Amazonía peruana?", options: ["Marañón", "Ucayali", "Amazonas", "Putumayo"], correctIndex: 2 },
      { question: "¿Cuál es el clima predominante en la Costa peruana?", options: ["Tropical húmedo", "Desértico con neblina (garúa)", "Templado lluvioso", "Alpino"], correctIndex: 1 },
      { question: "¿En qué región se encuentra el Lago Titicaca?", options: ["Junín", "Puno", "Cusco", "Tacna"], correctIndex: 1 },
      { question: "¿Cuál es el producto de exportación más importante del Perú?", options: ["Café", "Cobre", "Pescado", "Coca"], correctIndex: 1 },
    ],
    dificil: [
      { question: "¿Qué placa tectónica se encuentra bajo la costa occidental del Perú?", options: ["Placa Norteamericana", "Placa de Nazca", "Placa del Pacífico", "Placa Sudamericana"], correctIndex: 1 },
      { question: "¿A qué altura aproximada se encuentra el paso de la Cordillera Blanca más alto?", options: ["4,000 m.s.n.m.", "5,000 m.s.n.m.", "6,000 m.s.n.m.", "7,000 m.s.n.m."], correctIndex: 2 },
      { question: "Según el Censo 2017, ¿cuál es la población aproximada del Perú?", options: ["27 millones", "30 millones", "33 millones", "37 millones"], correctIndex: 2 },
      { question: "¿Qué corriente marina fría baña las costas peruanas y provoca el Fenómeno de El Niño?", options: ["Corriente del Golfo", "Corriente de Humboldt", "Corriente del Caribe", "Corriente del Labrador"], correctIndex: 1 },
      { question: "¿Cuál es el pico más alto del Perú y de la cordillera peruana?", options: ["Nevado Huascarán", "Nevado Ausangate", "Nevado Misti", "Yerupajá"], correctIndex: 0 },
    ],
  },
  tabla_periodica: {
    facil: [
      { question: "¿Qué indica el número atómico de un elemento?", options: ["Número de neutrones", "Número de protones", "Número de electrones en total", "Masa atómica"], correctIndex: 1 },
      { question: "¿Cuántos grupos (columnas) tiene la tabla periódica?", options: ["7", "12", "18", "20"], correctIndex: 2 },
      { question: "¿A qué grupo pertenecen los gases nobles?", options: ["Grupo 1", "Grupo 2", "Grupo 17", "Grupo 18"], correctIndex: 3 },
      { question: "¿Cuál es el símbolo químico del sodio?", options: ["So", "Na", "Sd", "No"], correctIndex: 1 },
      { question: "¿Cuántos períodos (filas) tiene la tabla periódica?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    ],
    medio: [
      { question: "¿Qué elemento tiene la configuración electrónica 1s² 2s² 2p⁶ 3s¹?", options: ["Litio (Li)", "Sodio (Na)", "Potasio (K)", "Magnesio (Mg)"], correctIndex: 1 },
      { question: "Al atravesar un período de izquierda a derecha, el radio atómico:", options: ["Aumenta", "Disminuye", "Se mantiene igual", "Primero aumenta y luego disminuye"], correctIndex: 1 },
      { question: "¿Qué elementos son los metales alcalinos?", options: ["Grupo 2", "Grupo 13", "Grupo 1 (excepto H)", "Grupo 17"], correctIndex: 2 },
      { question: "¿Cuál es la configuración electrónica del carbono (Z=6)?", options: ["1s² 2s² 2p²", "1s² 2s² 2p⁴", "1s² 2s² 2p⁶ 3s²", "1s² 2s⁴"], correctIndex: 0 },
      { question: "¿En qué bloque se encuentran los metales de transición?", options: ["Bloque s", "Bloque p", "Bloque d", "Bloque f"], correctIndex: 2 },
    ],
    dificil: [
      { question: "¿Qué tiende periódica describe la tendencia de ganar electrones en los no metales?", options: ["Radio atómico", "Energía de ionización", "Electronegatividad", "Masa atómica"], correctIndex: 2 },
      { question: "¿Cuál de estos elementos tiene mayor energía de ionización?", options: ["Li", "Na", "F", "Cs"], correctIndex: 2 },
      { question: "¿En qué período y grupo se encuentra el hierro (Fe)?", options: ["Período 4, grupo 8", "Período 5, grupo 6", "Período 4, grupo 12", "Período 3, grupo 8"], correctIndex: 0 },
      { question: "¿Qué elemento tiene mayor radio atómico dentro del grupo 1?", options: ["Litio (Li)", "Sodio (Na)", "Potasio (K)", "Francio (Fr)"], correctIndex: 3 },
      { question: "¿Cuántos electrones de valencia tiene el fósforo (P)?", options: ["3", "4", "5", "6"], correctIndex: 2 },
    ],
  },
  enlaces_quimicos: {
    facil: [
      { question: "¿Qué tipo de enlace se forma entre un metal y un no metal?", options: ["Covalente", "Metálico", "Iónico", "Covalente polar"], correctIndex: 2 },
      { question: "¿Cuántos electrones comparten los átomos en un enlace covalente doble?", options: ["1", "2", "4", "6"], correctIndex: 2 },
      { question: "¿Qué tipo de enlace hay en el metal puro, como el cobre (Cu)?", options: ["Iónico", "Covalente", "Metálico", "Van der Waals"], correctIndex: 2 },
      { question: "¿Qué molécula tiene un enlace covalente no polar?", options: ["HCl", "H₂O", "H₂", "NaCl"], correctIndex: 2 },
      { question: "¿Qué átomo tiene mayor tendencia a ganar electrones?", options: ["Na", "Mg", "Cl", "Ca"], correctIndex: 2 },
    ],
    medio: [
      { question: "Según VSEPR, ¿cuál es la geometría de CH₄?", options: ["Lineal", "Trigonal plana", "Tetraédrica", "Angular"], correctIndex: 2 },
      { question: "¿Qué tipo de enlace tiene mayor energía de enlace: simple, doble o triple?", options: ["Simple", "Doble", "Triple", "Todas son iguales"], correctIndex: 2 },
      { question: "¿Qué molécula es apolar a pesar de tener enlaces polares?", options: ["H₂O", "CO₂", "NH₃", "HCl"], correctIndex: 1 },
      { question: "¿Cuál es la geometría molecular del agua (H₂O)?", options: ["Lineal", "Tetraédrica", "Angular", "Trigonal plana"], correctIndex: 2 },
      { question: "¿Qué compuesto tiene un enlace predominantemente iónico?", options: ["CO₂", "H₂O", "NaCl", "CH₄"], correctIndex: 2 },
    ],
    dificil: [
      { question: "Según VSEPR, ¿cuántos pares libres tiene el nitrógeno en NH₃?", options: ["0", "1", "2", "3"], correctIndex: 1 },
      { question: "¿Cuál es la geometría molecular de CO₂ según VSEPR?", options: ["Angular", "Tetraédrica", "Trigonal plana", "Lineal"], correctIndex: 3 },
      { question: "¿Qué enlace es más polar: H-F, H-Cl, H-Br o H-I?", options: ["H-F", "H-Cl", "H-Br", "H-I"], correctIndex: 0 },
      { question: "¿Cuál es la energía reticular aproximada del NaCl?", options: ["100 kJ/mol", "400 kJ/mol", "800 kJ/mol", "1600 kJ/mol"], correctIndex: 2 },
      { question: "¿Qué molécula tiene hibridación sp² en el carbono central?", options: ["CH₄", "C₂H₄", "C₂H₂", "CO₂"], correctIndex: 1 },
    ],
  },
  reacciones_quimicas: {
    facil: [
      { question: "¿Qué tipo de reacción es: 2H₂ + O₂ → 2H₂O?", options: ["Descomposición", "Síntesis", "Sustitución", "Doble sustitución"], correctIndex: 1 },
      { question: "En una ecuación balanceada, ¿qué se conserva en ambos lados?", options: ["Solo la masa", "Solo el volumen", "La masa y los átomos", "La energía"], correctIndex: 2 },
      { question: "¿Qué tipo de reacción ocurre cuando un metal reemplaza a otro en un compuesto?", options: ["Síntesis", "Descomposición", "Sustitución simple", "Combustión"], correctIndex: 2 },
      { question: "¿Cuántos moles de agua se producen al reaccionar 1 mol de H₂ con exceso de O₂?", options: ["0.5 mol", "1 mol", "2 mol", "4 mol"], correctIndex: 1 },
      { question: "¿Qué coeficiente balancea el oxígeno en: _CH₄ + _O₂ → CO₂ + _H₂O?", options: ["1", "2", "3", "4"], correctIndex: 1 },
    ],
    medio: [
      { question: "En la reacción: Fe + CuSO₄ → FeSO₄ + Cu, ¿qué tipo de reacción es?", options: ["Combustión", "Descomposición", "Sustitución simple", "Doble sustitución"], correctIndex: 2 },
      { question: "¿Cuántos gramos de NaCl se obtienen de 2 moles de Na reaccionando con Cl₂?", options: ["58.5 g", "117 g", "234 g", "468 g"], correctIndex: 1 },
      { question: "¿Qué es el reagente limitante en una reacción?", options: ["El que sobra", "El que se consume primero", "El que está en exceso", "El producto principal"], correctIndex: 1 },
      { question: "En: 2Na + 2H₂O → 2NaOH + H₂, ¿cuántos moles de H₂ se producen con 4 moles de Na?", options: ["1 mol", "2 mol", "3 mol", "4 mol"], correctIndex: 1 },
      { question: "¿Qué tipo de reacción es la neutralización?", options: ["Síntesis", "Doble sustitución", "Descomposición", "Sustitución simple"], correctIndex: 1 },
    ],
    dificil: [
      { question: "¿Cuántos gramos de CaCO₃ se necesitan para producir 5.6 g de CaO?", options: ["5 g", "10 g", "20 g", "50 g"], correctIndex: 1 },
      { question: "En: 4Al + 3O₂ → 2Al₂O₃, si reaccionan 5.4 g de Al con exceso de O₂, ¿cuántos gramos de Al₂O₃ se forman?", options: ["5.1 g", "10.2 g", "20.4 g", "40.8 g"], correctIndex: 1 },
      { question: "¿Cuál es el reagente limitante si reaccionan 3 mol de N₂ con 8 mol de H₂ según N₂ + 3H₂ → 2NH₃?", options: ["N₂", "H₂", "Los dos se agotan juntos", "Ninguno"], correctIndex: 1 },
      { question: "¿Cuántos moles de gas se producen al quemar完全amente 2 moles de C₃H₈ (propano)?", options: ["8 mol", "10 mol", "12 mol", "14 mol"], correctIndex: 2 },
      { question: "En una valoración, si 25 mL de NaOH 0.1 M neutralizan HCl, ¿cuántos moles de HCl había?", options: ["0.0025 mol", "0.025 mol", "0.25 mol", "2.5 mol"], correctIndex: 1 },
    ],
  },
  acidos_bases: {
    facil: [
      { question: "¿Qué valor de pH indica un medio ácido?", options: ["pH = 7", "pH > 7", "pH < 7", "pH = 0"], correctIndex: 2 },
      { question: "¿Qué indicador se vuelve rojo en medio ácido?", options: ["Fenolftaleína", "Azul de bromotimol", "Naranja de metilo", "Litmus"], correctIndex: 2 },
      { question: "¿Cuál es el pH del agua pura a 25°C?", options: ["0", "1", "7", "14"], correctIndex: 2 },
      { question: "Un ácidos según Arrhenius produce en solución acuosa:", options: ["OH⁻", "H⁺", "Na⁺", "Cl⁻"], correctIndex: 1 },
      { question: "¿Qué sustancia es una base según Brønsted-Lowry?", options: ["Donador de protones", "Aceptor de protones", "Donador de electrones", "Aceptor de electrones"], correctIndex: 1 },
    ],
    medio: [
      { question: "¿Qué indica un pH de 3?", options: ["Neutral", "Ácido fuerte", "Ácido débil", "Base débil"], correctIndex: 1 },
      { question: "¿Qué indicador se vuelve rosado en solución básica?", options: ["Azul de metilo", "Fenolftaleína", "Naranja de metilo", "Indicador universal"], correctIndex: 1 },
      { question: "¿Cuál es el producto de la neutralización de HCl + NaOH?", options: ["NaCl + H₂O", "NaOH + HCl", "NaCl + H₂", "Na + H₂O"], correctIndex: 0 },
      { question: "Un buffer (amortiguador) se prepara mezclando:", options: ["Un ácido fuerte y una base fuerte", "Un ácido débil y su base conjugada", "Dos ácidos débiles", "Dos bases fuertes"], correctIndex: 1 },
      { question: "¿Qué volumen de NaOH 0.1 M se necesita para neutralizar 50 mL de HCl 0.1 M?", options: ["25 mL", "50 mL", "100 mL", "200 mL"], correctIndex: 1 },
    ],
    dificil: [
      { question: "¿Cuál es el pH de una solución de HCl 0.001 M?", options: ["1", "2", "3", "4"], correctIndex: 2 },
      { question: "En una titulación de ácido débil con base fuerte, el punto de equivalencia tiene pH:", options: ["7", "Menor que 7", "Mayor que 7", "Depende del ácido"], correctIndex: 2 },
      { question: "¿Cuál es la concentración de H⁺ en una solución con pH = 4.5?", options: ["3.16 × 10⁻⁵ M", "3.16 × 10⁻⁴ M", "3.16 × 10⁻³ M", "3.16 × 10⁻⁶ M"], correctIndex: 0 },
      { question: "Un buffer de acetato de sodio y ácido acético tiene pH = pKa cuando:", options: ["[ácido] > [base conjugada]", "[ácido] = [base conjugada]", "[ácido] < [base conjugada]", "pH = 7"], correctIndex: 1 },
      { question: "¿Qué pH tiene una solución 0.01 M de NaOH?", options: ["2", "4", "10", "12"], correctIndex: 3 },
    ],
  },
  quimica_organica: {
    facil: [
      { question: "¿Qué elemento es siempre parte de los compuestos orgánicos?", options: ["Hierro", "Carbono", "Oro", "Oxígeno"], correctIndex: 1 },
      { question: "¿Cuántos átomos de hidrógeno tiene el metano (CH₄)?", options: ["1", "2", "4", "6"], correctIndex: 2 },
      { question: "¿Qué tipo de hidrocarbono tiene solo enlaces simples?", options: ["Alqueno", "Alquino", "Alcano", "Aromático"], correctIndex: 2 },
      { question: "¿Qué grupo funcional tiene un alcohol?", options: ["-COOH", "-OH", "-NH₂", "-CHO"], correctIndex: 1 },
      { question: "¿Cuántos carbonos tiene el etano?", options: ["1", "2", "3", "4"], correctIndex: 1 },
    ],
    medio: [
      { question: "¿Cuál es la fórmula general de los alcanos?", options: ["CₙH₂ₙ", "CₙH₂ₙ₊₂", "CₙH₂ₙ₋₂", "CₙHₙ"], correctIndex: 1 },
      { question: "¿Qué grupo funcional distingue a un ácido carboxílico?", options: ["-OH", "-CHO", "-COOH", "-NH₂"], correctIndex: 2 },
      { question: "¿Qué es un polímero?", options: ["Un ácido pequeño", "Una molécula grande formada por monómeros repetidos", "Un metal pesado", "Un gas noble"], correctIndex: 1 },
      { question: "¿Qué tipo de isomería se presenta cuando dos compuestos tienen la misma fórmula molecular pero diferente disposición espacial?", options: ["Constitucional", "Conformacional", "Geométrica", "Optica"], correctIndex: 2 },
      { question: "¿Qué reactivo se usa para detectar dobles enlaces en hidrocarburos?", options: ["Agua", "Agua oxigenada", "Agua de bromo (Br₂ acuoso)", "Agua salada"], correctIndex: 2 },
    ],
    dificil: [
      { question: "¿Cuántos isómeros estructurales tiene el butano (C₄H₁₀)?", options: ["1", "2", "3", "4"], correctIndex: 1 },
      { question: "¿Qué monómero forma el polietileno por polimerización?", options: ["Etanol", "Etileno (eteno)", "Etano", "Acetileno"], correctIndex: 1 },
      { question: "¿Qué tipo de polimerización ocurre cuando el estireno forma poliestireno?", options: ["Condensación", "Adición", "Escisión", "Copolimerización"], correctIndex: 1 },
      { question: "Un compuesto con fórmula molecular C₃H₆O puede ser:", options: ["Solo un aldehído", "Solo una cetona", "Un aldehído, una cetona o un alcohol insaturado", "Solo un alcohol saturado"], correctIndex: 2 },
      { question: "¿Qué grupo funcional tiene la acetona?", options: ["Aldehído", "Cetona", "Ácido carboxílico", "Éter"], correctIndex: 1 },
    ],
  },
  biologia_general: {
    facil: [
      { question: "¿Cuántos niveles de organización biológica existen desde el átomo hasta la biosfera?", options: ["5", "6", "7", "8"], correctIndex: 1 },
      { question: "¿Qué propiedad permite a los seres vivos mantener equilibrio interno?", options: ["Reproducción", "Homeostasis", "Metabolismo", "Crecimiento"], correctIndex: 1 },
      { question: "¿Cuál es la unidad básica de la vida?", options: ["El átomo", "La célula", "El tejido", "El órgano"], correctIndex: 1 },
      { question: "¿Qué paso del método científico consiste en hacer una predicción?", options: ["Observación", "Hipótesis", "Experimentación", "Conclusión"], correctIndex: 1 },
      { question: "¿Cuál de estas NO es una característica de los seres vivos?", options: ["Metabolismo", "Reproducción", "Fotografía", "Respuesta a estímulos"], correctIndex: 2 },
    ],
    medio: [
      { question: "¿Qué nivel de organización agrupa células del mismo tipo?", options: ["Órgano", "Tejido", "Sistema", "Organismo"], correctIndex: 1 },
      { question: "¿Cuál es el organismo encargado de regular la homeostasis en los mamíferos?", options: ["Corazón", "Hígado", "Sistema nervioso", "Pulmones"], correctIndex: 2 },
      { question: "¿Qué tipo de célula tiene núcleo definido?", options: ["Procariota", "Eucariota", "Bacteriana", "Arquea"], correctIndex: 1 },
      { question: "¿En qué consiste la respiración celular?", options: ["Captar luz solar", "Obtener energía de la glucosa", "Producir oxígeno", "Transportar nutrientes"], correctIndex: 1 },
      { question: "¿Qué afirmación sobre el ADN es correcta?", options: ["Solo se encuentra en bacterias", "Contiene las instrucciones para construir un organismo", "Es un tipo de proteína", "Solo está en las mitocondrias"], correctIndex: 1 },
    ],
    dificil: [
      { question: "¿Qué nivel de organización incluye a todos los seres vivos de un área determinada?", options: ["Población", "Comunidad", "Ecosistema", "Biosfera"], correctIndex: 2 },
      { question: "Si una célula pierde la capacidad de regular su concentración interna de iones, ¿qué proceso falla?", options: ["Reproducción", "Homeostasis", "Digestión", "Fotosíntesis"], correctIndex: 1 },
      { question: "¿Cuál es la diferencia principal entre un organismo unicelular y uno pluricelular?", options: ["El unicelular no tiene ADN", "El pluricelular tiene especialización celular", "El unicelular es procariota", "No hay diferencia real"], correctIndex: 1 },
      { question: "¿Qué componente celular es responsable de la producción de energía (ATP)?", options: ["Ribosoma", "Mitocondria", "Ribosoma", "Lisosoma"], correctIndex: 1 },
      { question: "¿En qué consiste la teoría celular según Schleiden y Schwann?", options: ["Toda la materia está hecha de átomos", "Todos los seres vivos están formados por células", "Las células solo se forman por generación espontánea", "Las células procariotas son las más antiguas"], correctIndex: 1 },
    ],
  },
  celulas: {
    facil: [
      { question: "¿Qué tipo de célula NO tiene núcleo definido?", options: ["Eucariota", "Procariota", "Animal", "Vegetal"], correctIndex: 1 },
      { question: "¿Qué organelo es la 'central energética' de la célula?", options: ["Ribosoma", "Mitocondria", "Lisosoma", "Centriolo"], correctIndex: 1 },
      { question: "¿Qué proceso convierte la luz solar en energía química?", options: ["Respiración", "Fotosíntesis", "Fermentación", "Oxidación"], correctIndex: 1 },
      { question: "¿Qué estructura rodea a la célula y controla lo que entra y sale?", options: ["Pared celular", "Membrana plasmática", "Núcleo", "Citoplasma"], correctIndex: 1 },
      { question: "¿Qué organelo produce ribosomas en la célula eucariota?", options: ["Mitocondria", "Nucléolo", "Retículo endoplasmático", "Aparato de Golgi"], correctIndex: 1 },
    ],
    medio: [
      { question: "¿Cuál es la función principal del retículo endoplasmático rugoso?", options: ["Transportar lípidos", "Sintetizar proteínas", "Almacenar agua", "Destruir desechos"], correctIndex: 1 },
      { question: "¿Qué organelo modifica, empaqueta y secreta proteínas?", options: ["Ribosoma", "Aparato de Golgi", "Mitocondria", "Núcleo"], correctIndex: 1 },
      { question: "¿En qué organela ocurre la fotosíntesis?", options: ["Mitocondria", "Cloroplasto", "Ribosoma", "Lisosoma"], correctIndex: 1 },
      { question: "¿Qué tipo de transporte celular requiere energía (ATP)?", options: ["Difusión simple", "Ósmosis", "Transporte activo", "Difusión facilitada"], correctIndex: 2 },
      { question: "¿Cuál es la diferencia principal entre célula animal y vegetal?", options: ["La vegetal tiene mitocondrias", "La vegetal tiene pared celular y cloroplastos", "La animal tiene núcleo", "No hay diferencias"], correctIndex: 1 },
    ],
    dificil: [
      { question: "¿Qué tipo de ribosoma sintetiza proteínas destinadas a la exportación?", options: ["Ribosomas libres del citoplasma", "Ribosomas del RE rugoso", "Ribosomas mitocondriales", "Ribosomas del nucléolo"], correctIndex: 1 },
      { question: "¿Qué transporta electrones en la cadena de transporte de electrones mitocondrial?", options: ["ATP", "NADH y FADH₂", "Glucosa", "Oxígeno"], correctIndex: 1 },
      { question: "En la fotosíntesis, ¿qué molécula captura la energía luminosa?", options: ["Clorofila", "Hemoglobina", "Melanina", "Caroteno"], correctIndex: 0 },
      { question: "¿Qué proceso celular implica la digestión de componentes dañados por autofagia?", options: ["Mitosis", "Autofagia mediada por lisosomas", "Meiosis", "Citólisis"], correctIndex: 1 },
      { question: "¿Cuál es el producto final de la glucólisis aeróbica?", options: ["2 moléculas de piruvato", "6 moléculas de CO₂", "36-38 moléculas de ATP", "12 moléculas de agua"], correctIndex: 0 },
    ],
  },
  genetica: {
    facil: [
      { question: "¿Qué科学 Mendel con sus plantas de guisante?", options: ["Mutaciones al azar", "Leyes de la herencia", "Evolución por selección natural", "Fotosíntesis"], correctIndex: 1 },
      { question: "Si un organismo tiene genotipo Aa, ¿qué fenotipo expresa?", options: ["Siempre recesivo", "Siempre dominante", "Depende del ambiente", "Ambos por igual"], correctIndex: 1 },
      { question: "¿Qué es un genotipo?", options: ["La apariencia externa", "La composición genética completa", "Un solo gen dominante", "Una mutación"], correctIndex: 1 },
      { question: "¿Cuántos alelos hereda cada organismo diploide para un gen?", options: ["1", "2", "3", "4"], correctIndex: 1 },
      { question: "¿Qué significa que un allele es recesivo?", options: ["Siempre se expresa", "Solo se expresa en homocigosis", "Es más fuerte", "No tiene función"], correctIndex: 1 },
    ],
    medio: [
      { question: "En un cruce Aa × Aa, ¿qué proporción fenotípica se espera?", options: ["1:1", "2:1", "3:1", "1:2:1"], correctIndex: 2 },
      { question: "¿Qué es un cuadrado de Punnett?", options: ["Una tabla de multiplicar", "Una herramienta para predecir cruces genéticos", "Un tipo de mutación", "Un diagrama de ADN"], correctIndex: 1 },
      { question: "¿Cuántos cromosomas tiene un humano diploide?", options: ["23", "44", "46", "48"], correctIndex: 2 },
      { question: "Si A es dominante sobre a, ¿qué genotype produce fenotipo recesivo?", options: ["AA", "Aa", "aa", "Aa y aa"], correctIndex: 2 },
      { question: "¿Qué es una mutación puntual?", options: ["Cambio en un solo nucleótido", "Pérdida de un cromosoma completo", "Duplicación de todo el genoma", "Cambio en la forma de la célula"], correctIndex: 0 },
    ],
    dificil: [
      { question: "¿Qué tipo de herencia explica que los hijos tengan rasgos intermedios entre los padres?", options: ["Dominancia completa", "Dominancia incompleta", "Epistasia", "Ley de segregación"], correctIndex: 1 },
      { question: "En un cruce dihibrido AaBb × AaBb, ¿cuántas combinaciones genotípicas diferentes se producen?", options: ["4", "6", "9", "16"], correctIndex: 2 },
      { question: "¿Qué es el ligamiento génico?", options: ["Genes que siempre se heredan juntos por estar en el mismo cromosoma", "Genes que interactúan para producir un fenotipo", "Genes que solo se expresan en hombres", "Genes que causan enfermedades"], correctIndex: 0 },
      { question: "¿Qué酶 sintetiza nuevas cadenas de ADN durante la replicación?", options: ["ARN polimerasa", "ADN polimerasa", "Ligasa", "Helicasa"], correctIndex: 1 },
      { question: "¿Qué tipo de mutación cromosómica involucra la pérdida de un segmento del cromosoma?", options: ["Duplicación", "Inversión", "Deleción", "Translocación"], correctIndex: 2 },
    ],
  },
  ecologia: {
    facil: [
      { question: "¿Qué es un ecosistema?", options: ["Solo los animales de una zona", "Los seres vivos y su ambiente físico", "Un tipo de bioma", "Una cadena alimenticia"], correctIndex: 1 },
      { question: "¿Qué organismo inicia la cadena alimenticia?", options: ["El carnívoro", "El productor (planta)", "El decomposer", "El herbívoro"], correctIndex: 1 },
      { question: "¿Cuántos biomas principales hay en la Tierra?", options: ["3", "5", "6", "10"], correctIndex: 2 },
      { question: "¿Qué es la biodiversidad?", options: ["La cantidad de agua en un ecosistema", "La variedad de seres vivos en un área", "El número de depredadores", "La cantidad de plantas"], correctIndex: 1 },
      { question: "¿Cuál es un problema ambiental causado por la deforestación?", options: ["Aumento de oxígeno", "Pérdida de hábitat", "Enfriamiento global", "Aumento de biodiversidad"], correctIndex: 1 },
    ],
    medio: [
      { question: "¿Qué componente biótico consume organismos muertos?", options: ["Productor", "Consumidor primario", "Descomponedor", "Depredador"], correctIndex: 2 },
      { question: "¿Qué es una red alimenticia?", options: ["Una sola cadena de alimentación", "Interconexión de múltiples cadenas alimenticias", "Una trampa para insectos", "Una red de cables subterráneos"], correctIndex: 1 },
      { question: "¿Qué bioma se caracteriza por temperaturas extremadamente bajas y poca precipitación?", options: ["Selva tropical", "Tundra", "Bosque templado", "Pradera"], correctIndex: 1 },
      { question: "¿Qué es el efecto invernadero?", options: ["Enfriamiento de la Tierra por gases", "Calentamiento de la Tierra por gases que atrapan calor", "Ozono que protege del sol", "Lluvia ácida"], correctIndex: 1 },
      { question: "¿Qué porcentaje de energía se transfiere de un nivel trófico al siguiente?", options: ["100%", "50%", "10%", "1%"], correctIndex: 2 },
    ],
    dificil: [
      { question: "¿Qué es la sucesión ecológica primaria?", options: ["Recuperación de un ecosistema tras un incendio", "Colonización de un área nueva sin suelo previo", "Cambio estacional de especies", "Migración de animales"], correctIndex: 1 },
      { question: "¿Qué fenómeno ecológico describe el equilibrio entre depredadores y presas?", options: ["Simbiosis", "Ciclo de Lotka-Volterra", "Competencia interespecífica", "Mutualismo"], correctIndex: 1 },
      { question: "¿Qué contaminante provoca la acidificación de los océanos?", options: ["CO₂", "Plomo", "Mercurio", "Ozono"], correctIndex: 0 },
      { question: "¿Qué es un punto de inflexión en un ecosistema?", options: ["El momento de máxima biodiversidad", "Un cambio irreversible en el estado del ecosistema", "La estación seca", "El pico de población humana"], correctIndex: 1 },
      { question: "¿Qué impacto tiene la eutrofización en un cuerpo de agua?", options: ["Aumento de oxígeno", "Muerte de peces por falta de oxígeno", "Enfriamiento del agua", "Aumento de pH"], correctIndex: 1 },
    ],
  },
  anatomia_humana: {
    facil: [
      { question: "¿Cuántos huesos tiene aproximadamente un adulto humano?", options: ["106", "206", "306", "406"], correctIndex: 1 },
      { question: "¿Qué sistema protege los órganos internos del cuerpo?", options: ["Nervioso", "Digestivo", "Esquelético", "Reproductor"], correctIndex: 2 },
      { question: "¿Qué órgano bombea la sangre por todo el cuerpo?", options: ["Pulmón", "Hígado", "Corazón", "Riñón"], correctIndex: 2 },
      { question: "¿Cuál es la función principal de los pulmones?", options: ["Digirir alimentos", "Intercambio gaseoso", "Filtrar la sangre", "Producir hormonas"], correctIndex: 1 },
      { question: "¿Qué órgano del sistema digestivo absorbe los nutrientes?", options: ["Estómago", "Intestino delgado", "Hígado", "Páncreas"], correctIndex: 1 },
    ],
    medio: [
      { question: "¿Qué hueso es el más largo del cuerpo humano?", options: ["Húmero", "Fémur", "Tibia", "Peroné"], correctIndex: 1 },
      { question: "¿Qué tipo de músculo se contrae voluntariamente?", options: ["Liso", "Cardíaco", "Esquelético", "Visceral"], correctIndex: 2 },
      { question: "¿Cuál es la función de los glóbulos rojos?", options: ["Combatir infecciones", "Transportar oxígeno", "Coagular la sangre", "Producir hormonas"], correctIndex: 1 },
      { question: "¿Qué cámara del corazón recibe la sangre venosa del cuerpo?", options: ["Aurícula izquierda", "Ventrículo izquierdo", "Aurícula derecha", "Ventrículo derecho"], correctIndex: 2 },
      { question: "¿Qué gas se elimina al exhalar?", options: ["Oxígeno", "Nitrógeno", "Dióxido de carbono", "Hidrógeno"], correctIndex: 2 },
    ],
    dificil: [
      { question: "¿Qué válvula separa la aurícula izquierda del ventrículo izquierdo?", options: ["Tricúspide", "Mitral (bicúspide)", "Aórtica", "Pulmonar"], correctIndex: 1 },
      { question: "¿En qué parte del intestino delgado se absorben la mayoría de los nutrientes?", options: ["Duodeno", "Yeyuno", "Íleon", "Colon"], correctIndex: 1 },
      { question: "¿Qué estructura ósea protege al bulbo raquídeo?", options: ["Cráneo", "Vértebra atlas", "Vértebra axis", "Occipital"], correctIndex: 2 },
      { question: "¿Cuál es la función del diafragma en la respiración?", options: ["Purificar el aire", "Crear presión para inhalar y exhalar", "Producir moco", "Almacenar aire"], correctIndex: 1 },
      { question: "¿Qué enzima digestiva producida en el páncreas descompone las proteínas?", options: ["Amilasa", "Lipasa", "Tripsina", "Maltasa"], correctIndex: 2 },
    ],
  },
  geografia_fisica: {
    facil: [
      { question: "¿Cuántos continentes hay en la Tierra?", options: ["5", "6", "7", "8"], correctIndex: 2 },
      { question: "¿Cuál es el océano más grande del mundo?", options: ["Atlántico", "Índico", "Pacífico", "Ártico"], correctIndex: 2 },
      { question: "¿Qué placa tectónica se ubica bajo el océano Pacífico oriental?", options: ["Sudamericana", "Norteamericana", "Nazca", "Antártica"], correctIndex: 2 },
      { question: "¿Cuál es el río más largo del mundo?", options: ["Amazonas", "Nilo", "Misisipi", "Yangtsé"], correctIndex: 0 },
      { question: "¿Qué tipo de relieve domina la superficie terrestre?", options: ["Montañas", "Llanuras", "Mesetas", "Volcanes"], correctIndex: 1 },
    ],
    medio: [
      { question: "¿Qué causa principal forma las montañas?", options: ["Erosión del viento", "Movimiento de placas tectónicas", "Actividad volcánica", "Glaciares"], correctIndex: 1 },
      { question: "¿Qué tipo de clima se caracteriza por veranos calurosos e inviernos fríos?", options: ["Tropical", "Desértico", "Continental", "Polar"], correctIndex: 2 },
      { question: "¿Qué corriente marina fría baña las costas occidentales de Sudamérica?", options: ["Corriente del Golfo", "Corriente de Humboldt", "Corriente del Labrador", "Corriente del Kuroshio"], correctIndex: 1 },
      { question: "¿Qué porcentaje de la superficie terrestre está cubierto por agua?", options: ["51%", "61%", "71%", "81%"], correctIndex: 2 },
      { question: "¿Qué tipo de placa tectónica se encuentra bajo los continentes?", options: ["Oceánica", "Continental", "Mixta", "Subducción"], correctIndex: 1 },
    ],
    dificil: [
      { question: "¿Qué proceso tectónico forma los volcanes en el Cinturón de Fuego del Pacífico?", options: ["Divergencia oceánica", "Subducción de placa oceánica bajo continental", "Placa continental bajo oceánica", "Choque de dos placas continentales"], correctIndex: 1 },
      { question: "Según la clasificación de Köppen, ¿qué tipo de clima tiene Lima, Perú?", options: ["Tropical húmedo (Af)", "Desértico frío (BWn)", "Templado húmedo (Cfb)", "Polar (EF)"], correctIndex: 1 },
      { question: "¿Cuál es el punto más profundo del océano?", options: ["Fosa de las Marianas", "Fosa de Puerto Rico", "Trinchera de Tonga", "Fosa de Java"], correctIndex: 0 },
      { question: "¿Qué proceso geológico crea los valles en forma de U?", options: ["Erosión fluvial", "Acción glacial", "Movimiento sísmico", "Actividad volcánica"], correctIndex: 1 },
      { question: "¿Qué escala mide la intensidad de un terremoto?", options: ["Escala de Richter", "Escala de Mercalli", "Escala de Beaufort", "Escala de Mohs"], correctIndex: 0 },
    ],
  },
  geografia_peru: {
    facil: [
      { question: "¿Cuáles son las tres regiones naturales del Perú?", options: ["Norte, Centro, Sur", "Costa, Sierra, Selva", "Altiplano, Valle, Costa", "Montaña, Llanura, Costa"], correctIndex: 1 },
      { question: "¿En qué región natural se encuentra la ciudad de Cusco?", options: ["Costa", "Sierra", "Selva", "Valle"], correctIndex: 1 },
      { question: "¿Cuál es el río más importante de Lima?", options: ["Río Amazonas", "Río Urubamba", "Río Rímac", "Río Mantaro"], correctIndex: 2 },
      { question: "¿Cuántas regiones administrativas tiene el Perú?", options: ["24", "25", "32", "35"], correctIndex: 1 },
      { question: "¿En qué región del Perú se encuentra el Lago Titicaca?", options: ["Cusco", "Junín", "Puno", "Arequipa"], correctIndex: 2 },
    ],
    medio: [
      { question: "¿Cuál es la capital regional de la Amazonía peruana?", options: ["Iquitos", "Pucallpa", "Tarapoto", "Tumbes"], correctIndex: 0 },
      { question: "¿Qué recurso natural es el principal de exportación del Perú?", options: ["Café", "Cobre", "Pescado", "Algodón"], correctIndex: 1 },
      { question: "¿Qué fenómeno climático afecta periodicamente la costa peruana?", options: ["Ciclón tropical", "El Niño", "Tornado", "Monzón"], correctIndex: 1 },
      { question: "¿Cuál es la cordillera más alta del Perú?", options: ["Cordillera Central", "Cordillera Blanca", "Cordillera Oriental", "Cordillera Occidental"], correctIndex: 1 },
      { question: "¿Qué desierto cubre gran parte de la costa peruana?", options: ["Desierto del Sahara", "Desierto de Atacama", "Desierto costero del Perú", "Desierto de Gobi"], correctIndex: 2 },
    ],
    dificil: [
      { question: "¿A qué altura aproximada se encuentra el Huascarán, pico más alto del Perú?", options: ["5,500 m.s.n.m.", "6,000 m.s.n.m.", "6,768 m.s.n.m.", "7,500 m.s.n.m."], correctIndex: 2 },
      { question: "¿Qué río es el tributario más caudaloso del Amazonas dentro del Perú?", options: ["Río Marañón", "Río Ucayali", "Río Putumayo", "Río Napo"], correctIndex: 1 },
      { question: "¿Qué porcentaje del territorio peruano corresponde a la Amazonía?", options: ["30%", "45%", "60%", "75%"], correctIndex: 2 },
      { question: "¿En qué distrito de Lima se encuentra el centro histórico de la ciudad?", options: ["Miraflores", "San Isidro", "Cercado de Lima", "San Borja"], correctIndex: 2 },
      { question: "¿Qué mina peruana es una de las más grandes de cobre del mundo?", options: ["La Oroya", "Cerro Verde", "Antamina", "Yanacocha"], correctIndex: 2 },
    ],
  },
  ingles_basico: {
    facil: [
      { question: "What is the correct greeting for the morning?", options: ["Good night", "Good morning", "Good evening", "Good bye"], correctIndex: 1 },
      { question: "What number comes after nineteen?", options: ["Eighteen", "Twenty", "Seventeen", "Thirty"], correctIndex: 1 },
      { question: "What color is the sky on a clear day?", options: ["Red", "Green", "Blue", "Yellow"], correctIndex: 2 },
      { question: "Which word means a baby cat?", options: ["Puppy", "Kitten", "Cub", "Foal"], correctIndex: 1 },
      { question: "Complete: I ___ a student.", options: ["am", "is", "are", "be"], correctIndex: 0 },
    ],
    medio: [
      { question: "What is the plural of 'child'?", options: ["childs", "children", "childrens", "childes"], correctIndex: 1 },
      { question: "Which sentence is correct?", options: ["She don't like coffee", "She doesn't likes coffee", "She doesn't like coffee", "She not like coffee"], correctIndex: 2 },
      { question: "What does 'big' mean?", options: ["Pequeño", "Grande", "Rápido", "View"], correctIndex: 1 },
      { question: "Complete: There ___ two apples on the table.", options: ["is", "are", "am", "be"], correctIndex: 1 },
      { question: "What is the opposite of 'hot'?", options: ["Warm", "Cold", "Cool", "Mild"], correctIndex: 1 },
    ],
    dificil: [
      { question: "Which sentence uses the present continuous?", options: ["He is swim now", "He swimming now", "He is swimming now", "He swims now"], correctIndex: 2 },
      { question: "Choose the correct reported speech: 'I am tired,' she said.", options: ["She said I am tired", "She said she is tired", "She said she was tired", "She said she tired"], correctIndex: 2 },
      { question: "Complete: If I ___ you, I would study.", options: ["am", "was", "were", "be"], correctIndex: 2 },
      { question: "Which word is a synonym of 'quickly'?", options: ["Slowly", "Rapidly", "Carefully", "Quietly"], correctIndex: 1 },
      { question: "Which sentence is correct: 'I have been waiting ___ 3 hours.'", options: ["since", "for", "from", "until"], correctIndex: 1 },
    ],
  },
  ingles_gramatica: {
    facil: [
      { question: "Which is the verb 'to be' for 'she'?", options: ["am", "is", "are", "be"], correctIndex: 1 },
      { question: "Complete: He ___ to school every day.", options: ["go", "goes", "going", "gone"], correctIndex: 1 },
      { question: "What is the past tense of 'play'?", options: ["played", "playd", "plaid", "playing"], correctIndex: 0 },
      { question: "Which article is correct: ___ apple.", options: ["a", "an", "the", "none"], correctIndex: 1 },
      { question: "Complete: She is ___ the bus stop.", options: ["in", "on", "at", "by"], correctIndex: 2 },
    ],
    medio: [
      { question: "Which sentence is past simple?", options: ["I eat pizza", "I ate pizza", "I will eat pizza", "I am eating"], correctIndex: 1 },
      { question: "Choose the correct future form.", options: ["I will go tomorrow", "I go tomorrow", "I going tomorrow"], correctIndex: 0 },
      { question: "Choose the correct preposition.", options: ["The cat is in the table", "The cat is on the table", "The cat is at the table"], correctIndex: 1 },
      { question: "They ___ not like vegetables.", options: ["does", "do", "is", "are"], correctIndex: 1 },
      { question: "She ___ a book right now.", options: ["reads", "is reading", "read", "will read"], correctIndex: 1 },
    ],
    dificil: [
      { question: "Which uses the present perfect?", options: ["I have went", "I have gone", "I have go", "I have going"], correctIndex: 1 },
      { question: "If it rains, I ___ stay home.", options: ["will", "would", "am", "do"], correctIndex: 0 },
      { question: "The cake ___ by Mary.", options: ["was baked", "baked", "is bake", "were baked"], correctIndex: 0 },
      { question: "Which is a comparative?", options: ["good", "better", "best", "well"], correctIndex: 1 },
      { question: "He has studied English ___ 2019.", options: ["for", "since", "from", "by"], correctIndex: 1 },
    ],
  },
  ingles_verbos: {
    facil: [
      { question: "Past of 'go'?", options: ["goed", "went", "goes", "going"], correctIndex: 1 },
      { question: "Past of 'see'?", options: ["seed", "saw", "seen", "seeing"], correctIndex: 1 },
      { question: "Past of 'eat'?", options: ["eated", "ate", "eat", "eating"], correctIndex: 1 },
      { question: "Past of 'write'?", options: ["writed", "wrote", "written", "writing"], correctIndex: 1 },
      { question: "Past of 'buy'?", options: ["buyed", "bought", "buys", "buying"], correctIndex: 1 },
    ],
    medio: [
      { question: "Past participle of 'sing'?", options: ["sang", "sung", "singed", "singing"], correctIndex: 1 },
      { question: "She has ___ her homework.", options: ["done", "did", "does", "doing"], correctIndex: 0 },
      { question: "Past of 'teach'?", options: ["teached", "taught", "teach", "teaching"], correctIndex: 1 },
      { question: "They have never ___ to London.", options: ["went", "been", "gone", "going"], correctIndex: 2 },
      { question: "Past of 'drive'?", options: ["drived", "drove", "driven", "drives"], correctIndex: 1 },
    ],
    dificil: [
      { question: "Which uses past perfect?", options: ["I had went", "I had gone", "I have gone"], correctIndex: 1 },
      { question: "By next year, I ___ here for five years.", options: ["will live", "will have lived", "will be living"], correctIndex: 1 },
      { question: "He ___ (swim) every weekend.", options: ["swim", "swims", "swam", "swimming"], correctIndex: 1 },
      { question: "Phrasal verb: Please ___ the lights.", options: ["turn on", "turn in", "turn off", "turn down"], correctIndex: 2 },
      { question: "She ___ (run) every morning.", options: ["run", "runs", "ran", "running"], correctIndex: 1 },
    ],
  },
  ingles_conversacion: {
    facil: [
      { question: "Greeting for the afternoon?", options: ["Good morning", "Good afternoon", "Good night", "Good bye"], correctIndex: 1 },
      { question: "When you meet someone for the first time:", options: ["Nice to meet you", "Goodbye", "See you", "Take care"], correctIndex: 0 },
      { question: "Ask someone's name:", options: ["What is your name?", "Where your name?", "How your name?", "Who your name?"], correctIndex: 0 },
      { question: "To order food:", options: ["I want", "I would like", "Give me", "This mine"], correctIndex: 1 },
      { question: "Ask for directions:", options: ["Where is the bus?", "What is the bus?", "How is the bus?", "Who is the bus?"], correctIndex: 0 },
    ],
    medio: [
      { question: "How are you? I'm ___.", options: ["fine", "goodly", "wellly", "nicely"], correctIndex: 0 },
      { question: "When you don't understand:", options: ["I don't know", "Could you repeat?", "I understand", "That's fine"], correctIndex: 1 },
      { question: "Ask for the price:", options: ["What is the cost?", "How much is this?", "How many is this?", "What price?"], correctIndex: 1 },
      { question: "Where ___ the nearest bank?", options: ["am", "is", "are", "be"], correctIndex: 1 },
      { question: "Leaving the restaurant:", options: ["I'm full", "Check please", "Good food", "I want more"], correctIndex: 1 },
    ],
    dificil: [
      { question: "A: I'm sorry for the delay. B: ___", options: ["No problem", "You're welcome", "That's right", "I don't"], correctIndex: 0 },
      { question: "Politely ask for slower speech:", options: ["Repeat please", "Could you speak more slowly?", "You fast", "Slow down"], correctIndex: 1 },
      { question: "Would you mind ___ the window?", options: ["open", "opening", "to open", "opened"], correctIndex: 1 },
      { question: "A: It might rain. B: ___", options: ["I hope so", "I hope not", "I don't think", "I think"], correctIndex: 1 },
      { question: "To make a suggestion:", options: ["You should try the pasta", "You must try", "You have to try"], correctIndex: 0 },
    ],
  },
};
